### ISSUE TITLE
[REQUEST] Possibility to automate Charging Pad

### ISSUE THREAD

**Issue by Faustvii** [GabrielOlvH/Industrial-Revolution#101]
**Description:**
- Would be awesome if the charging pad could interact with item pipe / hoppers, currently you can right click an item into it to charge it but there's no way to automate it, also the Charging Pad doesn't seem to be in the guide book of indrev-1.7.15-BETA.jar

**Reason:**
- Having the possibility to automate the charging pad would make it possible to charge items remotely with stuff like Entangled bags from Kibe

**Comment by GabrielOlvH** [comment]
Should be possible with the Lazuli Flux Container now.
