### ISSUE TITLE
[BUG] Farmer plants outside of range

### ISSUE THREAD

**Issue by echoofskyz** [GabrielOlvH/Industrial-Revolution#102]
**Description:**
- The farmer planted things outside of its range

**Steps to Reproduce:**
- im assuming that you could just put a farmer down in a large tilled area hit the range and watch as it filles in out side the box

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: All of Fabric 3

**Logs:**
- Uhh....

**Details:**
its on max range
![2021-01-27_20 15 58](https://user-images.githubusercontent.com/11953511/106080544-e1a9b800-60dc-11eb-9920-ada531285d6b.png)

**Comment by echoofskyz** [comment]
....... sorry about the rude comment, i didnt think i got the chat in my screen shot
just spent a while building a nice field area and then it just went past what it should have

**Comment by echoofskyz** [comment]
.... ill go look and try to commit a fix to that loop

**Comment by GabrielOlvH** [comment]
Thanks for reporting and don't worry about that comment hahah
This issue should already be fixed in the dev branch so it will be part of the next update

**Comment by echoofskyz** [comment]
Cool, thx for the great mod.
