### ISSUE TITLE
[BUG] Supernatural Crops aren't harvested right

### ISSUE THREAD

**Issue by Raikaru** [GabrielOlvH/Industrial-Revolution#106]
**Description:**
When you place down the Farmer it destroys the whole crop instead of harvesting without destroying which makes it just pick up seeds

**Steps to Reproduce:**
Put down Farmer around a crop from Supernatural Crops

**Technical Information:**
 - Minecraft:  1.16.5
 - Fabric API:  0.30
 - Industrial Revolution:  1.8 - BETA - RC5
 - Modpack: None

**Logs:**
None

**Comment by GabrielOlvH** [comment]
You have to enable the `enableIngotDropOnBreak` config from Supernatural Crops because the Farmer uses loot tables to get the drops.
