### ISSUE TITLE
[Question] Mining Rig Computer & Drill

### ISSUE THREAD

**Issue by Romz24** [GabrielOlvH/Industrial-Revolution#110]
How to connect **Mining Rig Computer** to **Drill**? As I did not try, I could not do it. I'm not saying that this is a bug, I just can't figure out how it should work.

![image](https://user-images.githubusercontent.com/2458113/108171663-e75b5200-710c-11eb-997d-9ce8f92922c9.png)

I also noticed that the names of some parts of the **Drill** are not displayed correctly.

![image](https://user-images.githubusercontent.com/2458113/108171364-79168f80-710c-11eb-98db-9565aa4f2934.png)

**Comment by Romz24** [comment]
I noticed another unpleasant bug, if you place **Drill Head** in **Drill**, then break **Drill**, after that **Drill Head** simply disappears and does not drop out.

**Comment by Romz24** [comment]
If there is an explosion next to Drill, only parts of it break, shouldn't it break completely?

![image](https://user-images.githubusercontent.com/2458113/108179287-7de04100-7116-11eb-90cc-eee005b241de.png)

**Comment by GabrielOlvH** [comment]
Already fixed in dev, the update will be released later today. The guide book has been updated to explain how the Mining Rig Computer works and also has a setup screenshot. [This video](https://twitter.com/notstevenatall/status/1328484305790758912?s=20) also explains it. Thanks for reporting.
