### ISSUE TITLE
[BUG] Cannot craft infuser due to bronze requirement

### ISSUE THREAD

**Issue by qxeen-elsa** [GabrielOlvH/Industrial-Revolution#112]
**Description:**
The infuser needs bronze to craft but to craft bronze you need an infuser to craft it, an unreachable catch-22

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution:

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
Fixed as of 1.8.1. Thanks for reporting.
