### ISSUE TITLE
[BUG] No picture in inventory and when placed 

### ISSUE THREAD

**Issue by matthew42904** [GabrielOlvH/Industrial-Revolution#120]
**Description:**
- all the machines dont have any pictures and when i place it it dose not have any graphic 

**Steps to Reproduce:**
- im using these mods
[new 3.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/6018786/new.3.txt)

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.30.3+1.16
 - Industrial Revolution: 1.8.6 beta
 - modpacks: none

**Logs:**
- 
[latest.log](https://github.com/GabrielOlvH/Industrial-Revolution/files/6018789/latest.log)

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.
![image](https://user-images.githubusercontent.com/43304608/108641636-44893780-746e-11eb-8d44-e897996d0c59.png)
![image](https://user-images.githubusercontent.com/43304608/108641672-7e5a3e00-746e-11eb-850d-dcdb357d4dcc.png)

**Comment by GabrielOlvH** [comment]
Sodium incompatibility, try using Indium or removing sodium.
