### ISSUE TITLE
[BUG] cant build any factory

### ISSUE THREAD

**Issue by matthew42904** [GabrielOlvH/Industrial-Revolution#121]
**Description:**
- it wont let me build the multi block factories. i tried floating, on the ground, and also there is no white blocks

**Steps to Reproduce:**
- place down a factory and build it and right click it and it will say structure not built

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.30.3
 - Industrial Revolution: 1.8.7

**Logs:**
[latest.log](https://github.com/GabrielOlvH/Industrial-Revolution/files/6022454/latest.log)

**Comment by GabrielOlvH** [comment]
Show screenshots of your factory.

**Comment by GabrielOlvH** [comment]
![image](https://user-images.githubusercontent.com/17054373/108723151-b57a2f00-7502-11eb-9e6b-928294f7c74b.png)
This works just fine.

**Comment by matthew42904** [comment]
dose rotation matter?

**Comment by matthew42904** [comment]
![image](https://user-images.githubusercontent.com/43304608/108724981-e99a2380-74f3-11eb-8816-724fa621fefd.png)

**Comment by GabrielOlvH** [comment]
Make sure the intakes are facing the right direction, the side with the black square should face the ducts.

**Comment by matthew42904** [comment]
now its working. i dont know why it didnt earlier. i had everything the same. thanks for your help
