### ISSUE TITLE
[REQUEST] Add possibility to configure modular items

### ISSUE THREAD

**Issue by illumeleet** [GabrielOlvH/Industrial-Revolution#125]
**Description:**
Basically what i'm asking for is some sort of gui \ keybind to configure installed modules.
e.g: decreasing range on modular drill with installed range modules \ turning on\off silk touch module, etc

**Reason:**
I think that'll be kinda useful.

**Comment by GabrielOlvH** [comment]
It already exists, go into the Controls menu and bind a key to "Modular item configuration"

**Comment by illumeleet** [comment]
Oh, sorry.
