### ISSUE TITLE
[BUG] so I can't confirgure any cables with the wrench. I tried restarting minecraft and nothing happened. idk what to do

### ISSUE THREAD

**Issue by BobPIckle1** [GabrielOlvH/Industrial-Revolution#128]
**Description:**
- Give a detailed explanation of the issue

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by andytxr** [comment]
First step: use the form to report your bug.

Second step: What are you trying to do? Configure the input and output of the machine or the power cable?

**Comment by GabrielOlvH** [comment]
"Configuring" cables isn't a feature (I don't even know what you mean exactly). If you still have questions, please open an issue with more information and fill the pertinent for fields or join the discord to discuss it.
