### ISSUE TITLE
[BUG] Invisible Textures

### ISSUE THREAD

**Issue by Legotech15** [GabrielOlvH/Industrial-Revolution#130]
**Description:**
- Unfortunately, the textures in the game are transparent

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.31.0
 - Industrial Revolution: 1.8.11-BETA
 - Modpack: own

**Logs:**
- https://paste.ee/p/NrUeB

**Comment by andytxr** [comment]
You will need Indium to make Sodium compatible with the Industrial Revolution. 

[https://cdn.discordapp.com/attachments/789062022439632898/807395194093436969/AOF3-SODIUM.zip](url) This is a zip with Sodium and Indium, extract it and put into your mods folder.
