### ISSUE TITLE
Im playing in 1.16.5 and the "gamer axe" has only a stick for a sprite and does no damage 

### ISSUE THREAD

**Issue by TheOffical** [GabrielOlvH/Industrial-Revolution#131]
**Description:**
- Give a detailed explanation of the issue

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by ProjectET** [comment]
1. There is no description, you need a description and detail what you have tried and what you have not.
2. you first need to charge the gamer axe in a charger or lapis flux container
3. after it is charged right click with the gamer axe equipped in your main hand.
