### ISSUE TITLE
[BUG] Lazuli Container MK3 Power Drain Loop 1.16.5

### ISSUE THREAD

**Issue by fzzyhmstrs** [GabrielOlvH/Industrial-Revolution#132]
**Description:**
- When fully charged, a Lazuli Container MK3 is looping through a power drain of approximately 15K LF every second or so (dropping to ~985K then rapidly charging to 998K-ish, then repeating over and over while draining power from the input line very rapidly). From what I can tell, the bug occurs when there is a Cable MK1 input. When there is input via MK2 cable, no looping occurs, or it's very difficult to trigger. Please see the two screenshots demonstrating the bugging setup and the functional setup. Only difference is the input line. 

Overall consistency of the bug was extremely low when troubleshooting. Sometimes I could achieve stable operation by disconnecting some parts of the output power network, disconnecting the input, then reconnecting. Sometimes that didn't work, and I got seemingly random outcomes of stability depending on which part of my gird I disconnected. Sometimes I got the instability with literally nothing connected except the MK1 input line. Sometimes I could achieve stability with a MK1 input.

**Steps to Reproduce:**
Was able to reproduce in a creative world when I added a couple MK1 Containers facing into the MK3 container as shown in my third screenshot below. I was NOT able to consistently achieve the instability with this setup (similar to the above inconsistency in my survival world). For instance, when I quit and reloaded the creative world I couldn't get the looping to occur even with the exact same setup. 

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.30.3+
 - Industrial Revolution: 1.8.11 BETA
 - Modpack: AOF3 (All of Fabric 3 - 2.6.10)

**Logs:**
Not a crash, so no logs to paste.

**Details:**
Buggy setup
![2021-03-16_21 25 30](https://user-images.githubusercontent.com/72876796/111406569-ec2e0a00-86a8-11eb-816e-79459c04ff0b.png)

Functional setup
![2021-03-16_21 20 47](https://user-images.githubusercontent.com/72876796/111406609-fbad5300-86a8-11eb-800a-f4716006f9eb.png)

Replicated looping via the below setup
![2021-03-16_21 53 28](https://user-images.githubusercontent.com/72876796/111406641-0962d880-86a9-11eb-95c3-897ad294db79.png)

**Comment by GabrielOlvH** [comment]
I've noticed a similar bug with other machines too but I was never able to reproduce it. Could you try reproducing it with the latest version of indrev? Cable logic has changed so maybe it was somehow fixed

**Comment by fzzyhmstrs** [comment]
> I've noticed a similar bug with other machines too but I was never able to reproduce it. Could you try reproducing it with the latest version of indrev? Cable logic has changed so maybe it was somehow fixed

Yes absolutely, I can try replicating it tonight in 1.8.13. I was only originally using 1.8.11 due to the modpack. I will also try updating it in a copy of the modpack world to see if there's any difference in results between indrev as a standalone mod compared to inside AOF3.

**Comment by fzzyhmstrs** [comment]
Tried replicating with 1.8.13 and cannot get any instability. It seems to have been fixed by the change in cable logic. I'll open an issue again if I see any instability in the future.
