### ISSUE TITLE
[REQUEST] Improve Input Handling for Multi-Input Machines (Solid Infuser Currently)

### ISSUE THREAD

**Issue by fzzyhmstrs** [GabrielOlvH/Industrial-Revolution#141]
**Description:**
For machines with multiple required inputs, specifically the solid infuser, it would be really nice if the machine restricted the inputs of valid combinations of materials. As it stands currently, either slot will accept any valid material from the same input hopper, pipe, etc, leading to clogged machines where both slots contain only one half of the recipe. My attached screenshot below illustrates the issue. My pipe system ran short on coal dust, so the slots clogged with iron dust, removing automation and requiring my manual intervention. A potential solution is to restrict the left and right input slots to certain halves of the recipes.  For example, iron dust can only be input into the left input slot, coal dust into the right; iron ingots or diamond dust into the left, nikolite dust into the right; and so on.

**Reason:**
As they currently function, it's very difficult to automate the solid infuser, and whatever other multi-input machines there are or might be in the future. They can easily clog with half of the required materials when that half happens to be in overabundance at a given period.

![2021-04-01_21 09 34](https://user-images.githubusercontent.com/72876796/113370158-2c3fee80-9331-11eb-8dae-df6d0e505f72.png)

**Comment by GabrielOlvH** [comment]
This is already solved in dev by using two different configuration modes: ``Input (First Slot)`` and ``Input (Second Slot)``. The update should be coming out soon, I'll leave this open for now as it isn't released yet.

**Comment by GabrielOlvH** [comment]
Implemented as of 1.9.0 which can be downloaded on curseforge.
