### ISSUE TITLE
[REQUEST] Nikola Monster

### ISSUE THREAD

**Issue by saltyseadoggo** [GabrielOlvH/Industrial-Revolution#142]
**Description:**
The title sounds like a five year old wrote it, but bear with me.
You're a few nights into a new playthrough with *Industrial Revolution* installed, perhaps returning to your home in the dark of night. It's raining, and you hear lightning around you, when you see through the trees what looks like a zombie with glowing blue veins across its head and arms. You cautiously approach to take a closer look, and you see a decrepit undead with deep blue skin laced with metal stitches in the skin of its arms and head, and bolts in the sides of its head, crackling with the energy of enriched Nikolite. How this creature came to be, you can only guess: perhaps the illagers, or another ancient race, dabbled in the same technology you are now, using it to create life much like Frankenstein's monster. In any case, you're in for a tough fight, but you will be rewarded with a fair sum of Nikolite dust and chunks of different ores that were previously woven into its body.

What I have dubbed the *Nikola Monster,* playing off of Frankenstein's monster with a name similar to the cryptid Grafton monster, would be a zombie variant that some forgotten beings dabbling in *Industrial Revolution's* technology created with rotten flesh and machine parts. It would spawn rarely anywhere regular mobs can, much like the witch, but would have greater chances of spawning during rainstorms or thunder storms. In addition, perhaps killing a zombie using a laser could turn it into a Nikola monster, much like how they can convert into drowned?
Nikola monsters should be stronger than the average zombie in some way, perhaps with higher health, damage and movement speed. If you're feeling adventurous in your programming, perhaps they could even unleash the same laser beam used by the laser block to attack?
Similarly to the witch, on death, they would drop some rotten flesh, Nikolite dust, and any of the ore chunks in fair quantities of each.

**Reason:**
I first thought of this idea as it pertains to modded skyblock playthroughs. None of *Industrial Revolution's* materials are obtainable in a skyblock scenario, as the only way to obtain them renewably is through the mining rig, which requires those materials to craft... so the map creator must either give the player a full blown mining rig as a starting item, or tack *IR's* raw resources onto mob loot tables, or make them craftable. None of these solutions are very graceful, I feel, whereas a flavourful mob would feel more intentional and polished.
Likewise, for regular playthroughs, this mob would bring extra lore, flavour and integration into the world to *Industrial Revolution.* Surely the player is not the only one to dabble in technology if it's practically child's play to assemble some basic machines? And what's a better enemy for a Minecraft technology mod than a Frankenstein's monster, an undead-like creature made with electricity and technology?

Obviously, this is just an idea that can be tweaked and tinkered with to your liking. The name and aesthetics need not be final. The general idea is a technology-based monster that can make *Industrial Revolution's* resources renewable until one can obtain the mining rig in skyblock, while also fitting with Minecraft's aesthetic and bringing some minor lore to the mod.
One more thing: I noticed on the All of Fabric 3 Discord that you mentioned art being a bit of a struggle for you, so I would be happy to take a shot at making a texture for this beastie if you like the idea.

**Comment by GabrielOlvH** [comment]
I appreciate the effort put into writing this and it sounds like it would be fun but not fitting for a tech mod, sorry. Maybe an addon someday.
