### ISSUE TITLE
Emerald vein for the mining rig

### ISSUE THREAD

**Issue by saltyseadoggo** [GabrielOlvH/Industrial-Revolution#144]
**Description:**
- Describe your suggestion with as many details as possible.

I would like to see a vein type added to the mining rig that yields emerald ore. I don't know enough about real world ore vein types to suggest where this vein should occur, what it should be called or what else should be in it aside from stone, but vanilla ore generation would suggest mountainous biomes to be a good place.

**Reason:**
- Why do you think your suggestion should be added?

Quite simply, having an emerald vein would mean that the mining rig makes emerald ore as a block ~~renewable~~ easier to obtain in large quantities, which it is not in vanilla. This allows it to be 'farmed' to obtain it in large quantities for builds, and also makes it obtainable in skyblock. The mining rig already makes all of the other vanilla and IR ore blocks ~~renewable~~ easier to obtain in large quantities, so why not emerald?

**Comment by GabrielOlvH** [comment]
Emerald has been part of some veins for a while now, forgot to close this issue. Thanks for the suggestion
