### ISSUE TITLE
[BUG] Blocks are missing when this mod is used with Sodium

### ISSUE THREAD

**Issue by nm17** [GabrielOlvH/Industrial-Revolution#149]
**Description:**

| Without Sodium | With Sodium |
|-|-|
| ![2021-04-10_13 12 54](https://user-images.githubusercontent.com/23419131/114265071-d38ee680-99ff-11eb-821b-8b7052e6850a.png) | ![2021-04-10_13 16 26](https://user-images.githubusercontent.com/23419131/114265073-d4c01380-99ff-11eb-9e96-26d52937da06.png) |
| ![2021-04-10_13 26 44](https://user-images.githubusercontent.com/23419131/114265174-6c256680-9a00-11eb-94c4-4673f1e0b6d3.png)  | ![2021-04-10_13 16 43](https://user-images.githubusercontent.com/23419131/114265075-d5f14080-99ff-11eb-82c3-be905d1e6ca7.png) |

**Steps to Reproduce:**
- Add this mod to your list of mods
- Add Sodium too
- Start up Minecraft
- See that some blocks don't have textures at all

**Technical Information:**
 - Minecraft: 1.16.5 on MultiMC 0.6.12-1438
 - Fabric API: 0.32.5+1.16
 - Industrial Revolution: 1.8.13-BETA
 - Modpack: None
 - Sodium: [Latest official release](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.16.3-0.1.0) and [my build of `1.16.x/next` branch](https://github.com/CaffeineMC/sodium-fabric/actions/runs/693537304)

**Logs:**
This gist has multiple files, check out `with_sodium.log` and `without_sodium.log`
https://gist.github.com/nm17/3fd76260e2f8f45d3b3e2ddc9a455a04

**Details:**
I've tried:
  - Changing java version
  - Changing texture packs and disabling them all
  - Disabling and enabling other mods to see if it would make a difference (in the end, it only happens with Sodium)

CPU: Intel(R) Core(TM) i5-9300H CPU
GPU: GeForce GTX 1650

I'm on Kubuntu 20.10 if that matters.

**Comment by nm17** [comment]
Nvm, I found #130. Please [add this](https://github.com/GabrielOlvH/Industrial-Revolution/issues/130#issuecomment-790534085) to the desctiption of the mod @GabrielOlvH

**Comment by nm17** [comment]
Also the discord link doesn't work now

**Comment by RemagOfficial** [comment]
> Also the discord link doesn't work now

https://discord.gg/dhecUAJFrT

**Comment by nm17** [comment]
> > Also the discord link doesn't work now
> 
> https://discord.gg/dhecUAJFrT

Check #industrial-revolution , I still can't access the file.

**Comment by GabrielOlvH** [comment]
Join the [All of Fabric Discord](https://discord.com/invite/6rkdm48) and check the FAQ channels. They have descriptions of how to do it and a ready to install zip with sodium and indium.
