### ISSUE TITLE
Ores are not spawning, they leave holes in the terrain gen

### ISSUE THREAD

**Issue by Dragon20C** [GabrielOlvH/Industrial-Revolution#15]
I made a new world in creative to test this since I tried it on survival and I have noticed that no ores were spawning, instead they left holes like the mod was removed, since I made 2 new worlds today the ore isnt spawning maybe a conflict between mods I do not know.

here is the list of mods I have installed:

[Mods installed.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/4967856/Mods.installed.txt)

If you look at the image, at the top left you can see the mini map and it shows holes which could suggest that the mod tried to spawn the ore but for some reason goes away.
![Ores not spawning](https://user-images.githubusercontent.com/15175043/88319562-3cb8b780-cd14-11ea-87a6-0378bf5a8a3f.png)

**Comment by GabrielOlvH** [comment]
Well this is weird, last time i tested it was working... Now I tested it myself and I had the same issue. I'll look into it and send a fix as soon as possible, sorry about the inconvenience!

**Comment by Dragon20C** [comment]
@GabrielOlvH thanks for a quick response, I know I might be extending a bit but are you willing to maybe add a command to so the ore gen can be redone I dont want to restart my world, of course if its too time consuming I understand!

**Comment by GabrielOlvH** [comment]
I'm not even sure how to do that, sorry, but you'll still be able to find new ores in new chunks though

**Comment by GabrielOlvH** [comment]
Fixed as of 1.2.0-BETA, which you can download [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3012763). Let me know if you still have any issues.

**Comment by Dragon20C** [comment]
@GabrielOlvH Thanks will test it now!
