### ISSUE TITLE
[BUG] SHIFT CLICKING IN ITEM FILTERS DUPES ITEMS!!!!!!!

### ISSUE THREAD

**Issue by Minecatr** [GabrielOlvH/Industrial-Revolution#157]
**Description:**
- Shift clicking into item pipe filters dupes the stackable item
to fix this disable shift clicking or fix tile entity
**Steps to Reproduce:**
- open item pipe filter shift click item and it wont go in instead it will dupe

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
Thanks for reporting, fixed as of 1.9.4-BETA.
