### ISSUE TITLE
[BUG] break a tank in survival

### ISSUE THREAD

**Issue by Minecatr** [GabrielOlvH/Industrial-Revolution#158]
**Description:**
- Im playing with some mods and I break a tank and the game crashes then I join and texture mapping breaks

**Steps to Reproduce:**
- break a tank

**Technical Information:**
 - Minecraft: 
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by Minecatr** [comment]
![image](https://user-images.githubusercontent.com/82689952/115154205-b08bb480-a047-11eb-9fdd-dcd228cf1970.png)

**Comment by GabrielOlvH** [comment]
Please send the logs after the crash

**Comment by Minecatr** [comment]
k

**Comment by Minecatr** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/18/21 1:09 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6)
	at net.minecraft.client.render.entity.ItemEntityRenderer.handler$cea000$render(ItemEntityRenderer:575)
	at net.minecraft.client.render.entity.ItemEntityRenderer.render(ItemEntityRenderer)
	at net.minecraft.client.render.entity.ItemEntityRenderer.render(ItemEntityRenderer:18)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1459)
	at net.minecraft.client.render.WorldRenderer.redirect$bai000$redirectRenderEntity(WorldRenderer:6428)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1219)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
	at net.minecraft.client.render.GameRenderer.redirect$bae000$redirectRenderingWorld(GameRenderer:3552)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 1302
	Entity Name: Tank
	Entity's Exact location: 162.35, 75.49, -309.73
	Entity's Block location: World: (162,75,-310), Chunk: (at 2,4,10 in 10,-20; contains blocks 160,0,-320 to 175,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.01, 0.20, 0.08
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Motion:[0.00825d,0.2d,0.077125d],Health:5s,Invulnerable:0b,Air:300s,OnGround:0b,PortalCooldown:0,Rotation:[-60.46875f,0.0f],FallDistance:0.0f,Item:{id:"indrev:tank",Count:1b,tag:{tanks:{0:{fluids:{}}},TransferConfig:{fluid:{AutoPush:1b,east:"NONE",south:"NONE",north:"NONE",west:"NONE",up:"NONE",down:"NONE",AutoPull:1b}}}},Pos:[162.35240173339844d,75.49272155761719d,-309.73370361328125d],PickupDelay:0s,Fire:-1s,UUID:[I;1587662342,1009795507,-1827754167,930343170],Age:0s}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:283)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.redirect$bai000$redirectRenderEntity(class_761.java:6428)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$bae000$redirectRenderingWorld(class_757.java:3552)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_916@1a857ce5
	Location: -0.11,-2.13,-0.90 - World: (-1,-3,-1), Chunk: (at 15,-1,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -27.815166
	Delta: 0.4599924
-- Affected level --
Details:
	All players: 1 total; [class_746['Minecatr'/448, l='ClientWorld minecraft:overworld', x=162.46, y=76.00, z=-308.84]]
	Chunk stats: Client Chunks (ImmPtl) 1055
	Level dimension: minecraft:overworld
	Level spawn location: World: (226,63,-161), Chunk: (at 2,3,15 in 14,-11; contains blocks 224,0,-176 to 239,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 92115 game time, 92115 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2581766872 bytes (2462 MB) / 6543114240 bytes (6240 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.9
		architectury: Architectury 1.10.139
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.9
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		blockus: Blockus 2.1.0+1.16.5
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.1.0
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.7
		cameraoverhaul: Camera Overhaul 1.2.2-fabric-universal
		cardinal-components-base: Cardinal Components API (base) 2.7.12
		cardinal-components-block: Cardinal Components API (blocks) 2.7.12
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.12
		cardinal-components-entity: Cardinal Components API (entities) 2.7.12
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-world: Cardinal Components API (worlds) 2.7.12
		castle_dungeons: Castle Dungeons 2.2
		chainmail: Chainmail 0.5.0
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.4.5
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		comforts: Comforts 0.0.2-1.16.5
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.2
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.0.0
		crawl: Crawl 0.8.2
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.13-1.16.5
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		deaths_wish: Death's Wish 1.4.0
		desolation: Desolation 1.1.1
		doomangelring: Doom Angel Ring 1.0.0
		dragonloot: DragonLoot 1.0.5
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.0
		durability_banks: Durability Banks 0.1.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		elevator: Elevator Mod 1.0.0
		enchant_giver: Enchant Giver 1.0.3
		enchantment_lore: EnchantmentLore 1.1.1+MC1.16.1-1.16.5
		entityculling: EntityCulling-Fabric 1.2.1
		expandedstorage: ExpandedStorage 5.6.33
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		factory: Factory 1.16.2-1.3.0
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.3.1
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		flesh2leather: Flesh2Leather 1.0.2
		fluidphysics: Fluid Physics 1.4.0+fabric-1.16.4
		flytre_lib: FlytreLib 0.2.8
		geckolib3: Geckolib 3.0.29
		go-fish: Go Fish 1.2.1-beta-1.16.4
		greater_eye: Greater Eye of Ender 1.1.5
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harvest: Harvest 1.2.12
		heartbond: Heartbond 1.0.0
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		imm_ptl_core: Immersive Portals Core 0.88
		immersive_portals: Immersive Portals 0.88
		indrev: Industrial Revolution 1.9.4-BETA
		infinitywaterbucket: Infinity Water Bucket 1.3-mc1.16.4-fabric
		invtrashslot: InvTrashSlot 1.0.2
		itemfilters: Item Filters 1605.2.4-build.30
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		kiln: Kiln 1.1.1+1.16.5
		kirin: Kirin UI 1.7-1.16.2
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		library_of_exile: Library of Exile 1.0.7
		limitedspawners: Limited Spawner 1.0.1
		lithium: Lithium 0.6.4
		magic_mirror: Magic Mirror 1.1
		magna: Magna 0.2.1-1.16.5
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		mcda: MC Dungeons Armors 1.3.8
		mcdw: MC Dungeons Weapons 3.0.7
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.8
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.6.5+mc1.16.5
		notenoughcrashes: Not Enough Crashes 3.1.8
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aeonbits_owner_owner: owner 1.0.12
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-50-FABRIC
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		presencefootsteps: Presence Footsteps r29+1.16.4
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.1-fabric
		retroitems: Retro Items 1.0.0
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rpgstats: RPGStats 3.2.6+1.16.5
		satin: Satin 1.5.1
		secretrooms: Secret Rooms 0.9.3+1.16.5
		sgod: Save Gear on Death 0.0.2
		simple_backpack: SimpleBackpack 1.0.38
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		smooth-chunks: Smooth Chunks 1.0.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		somnus: Somnus API 0.0.11-1.16.5
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.1.0
		team_reborn_energy: Energy 0.1.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trade: Trade 1.1.3
		transparent_cosmetics: Transparent Cosmetics 1.2.0
		trapexpansion: Trap Expansion 1.3.2
		tweed: Tweed API 3.0.0-beta.22
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		walljump: Wall-Jump! 1.3.3+1.16.1
		waystones: Waystones 1.1.1.1
		winged: Winged Mod 1.16.2-1.4.1
		xp_storage: XP Storage 1.4+1.16.5
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, null, minecraft:transparent_cosmetics, deaths_wish:deaths_wish_assetpack, Fabric Mods, slightguimodifications:cts_textures
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

Will this work??

**Comment by RemagOfficial** [comment]
could be immersive portals, I'm not the best with logs tho

**Comment by GabrielOlvH** [comment]
Some other mod is interfering with rendering, this is not caused by Industrial Revolution. [Mixintrace](https://github.com/comp500/mixintrace/tree/1.0.0) can help diagnose the issue (add it, crash the game again and send the new crash report here)

**Comment by GabrielOlvH** [comment]
Closing due to lack of response. This is unlikely caused by indrev.
