### ISSUE TITLE
[BUG] Error upon launching fabric server with indrev in mods folder

### ISSUE THREAD

**Issue by thereal123dprinter** [GabrielOlvH/Industrial-Revolution#159]
Launching a Fabric server with the mod and the required dependency will make it crash with the error "Could not find required mod: indrev requires {fabric @ [>=0.32.0]}"

**Steps to Reproduce:**
Install latest fabric server version
Put indrev and required dependency in mod folder
Launch server

**Technical Information:**
 - Minecraft: 
 1.16.5
 - Fabric API: 
 Latest
 - Industrial Revolution: 
 Latest
 - Modpack: 
 Only other mod is BYG
 

**Logs:**
- https://pastebin.com/cHpX2PZb

**Details:**
![image](https://user-images.githubusercontent.com/73493250/115778914-ecdb4f80-a37c-11eb-9272-3534f04a4959.png)
![image](https://user-images.githubusercontent.com/73493250/115778997-04b2d380-a37d-11eb-8f95-5a79ffcdcc35.png)

**Comment by RemagOfficial** [comment]
update fabric api

**Comment by thereal123dprinter** [comment]
much appreciated
