### ISSUE TITLE
[BUG] Energy Efficiency Enhancer does not work (increases power consumption rather than decreases)

### ISSUE THREAD

**Issue by ConanODoyle** [GabrielOlvH/Industrial-Revolution#165]
**Description:**
Energy Efficiency Enhancer increases power draw significantly for any machine

**Steps to Reproduce:**
Place and power a recycler, use an energy reader on it. It should say 8.0 LF/tick
Add an energy efficiency enhancer upgrade, it should now say 80 LF/tick
Add a second energy efficiency enhancer upgrade, it should now say 40 LF/tick

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.33.0
 - Industrial Revolution: 1.9.4 BETA
 - Modpack: All of Fabric 3 https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3282477

**Details:**
https://gfycat.com/IndolentTidyBushsqueaker

Notably, using a speed upgrade (I assume) properly increases the power usage to 16 LF/tick - adding an energy enhancer after that jumps total usage up to 160 LF/tick

**Comment by GabrielOlvH** [comment]
Energy Efficiency Enhancers have been removed as of 1.10.0-beta.1
