### ISSUE TITLE
[BUG] Ingame guide does not have a page on pumps

### ISSUE THREAD

**Issue by ConanODoyle** [GabrielOlvH/Industrial-Revolution#166]
**Description:**
Ingame guide does not have a page talking about pumps (recipe, how to use them/behavior)

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.33.0
 - Industrial Revolution: 1.9.4 BETA
 - Modpack: All of Fabric 3 https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3282477

**Comment by GabrielOlvH** [comment]
Fixed as of 1.9.9.

**Comment by evankimori** [comment]
Didn't want to post a new report for this question as this concerns the Guide as well, please inform if I should create new.

Is there a planned update for the Guide book RE: the introduction of Drains and their usage and doing a bit more detailed explanation on the usage of Servos w/liquids etc? I know the Guide is detailed but I've gotten some personal requests concerning detailing the guide from other users who don't seem to get a lot of the "obvious" nuances of the machines.

I'd be more than willing to contribute additional writeup to add to the Guide if needed. :)
