### ISSUE TITLE
[REQUEST] Optimize Pump Algorithm

### ISSUE THREAD

**Issue by hugeblank** [GabrielOlvH/Industrial-Revolution#171]
**Description:**
Currently the pump pulls from the nearest source blocks connected to the source it's pumping from. This leads to it not consuming all of the blocks on the layer it's on, which is not good if you're trying to completely remove a vast lake of lava.

**Reason:**
I think this should be fixed since it's realistic to complete a layer before moving on to the next (which is not what it does). My in game experience with the pump has been frustrating because of the current implementation.

**Comment by GabrielOlvH** [comment]
Just the first layer wouldn't be drained fully. When it goes down to the second one, the fluid on the top will flow down so it always keeps looking for sources until it can't find any.
The way the pump works is it only drains every 20 ticks and during these 20 ticks, it looks for X blocks until it finds a fluid source. This means the farther it goes the longer it takes to find a source block (shouldn't be heavily noticeable unless it's a huge lava lake). If I were to invert that logic it'd be much more slower than that as I'd have to find every single fluid block next to it before determining which one is the farthest, which would result in adding a small range and you having to move your pump more often.
