### ISSUE TITLE
[BUG] Servos randomly vanish

### ISSUE THREAD

**Issue by hugeblank** [GabrielOlvH/Industrial-Revolution#173]
**Description:**
- This is an inconsistent issue that keeps happening to my friends and I, where when a pipe is broken it has a seemingly random chance of not dropping the servo. I believe this happens when you remove the block the servo is attached to _before_ you break the pipe the servo is on. 

**Steps to Reproduce:**
- create a basic setup with two chests
- attach a servo on one to pipe items across
- break the chest the servo is attached to
- break pipe, servo may or may not drop

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: v0.32.5
 - Industrial Revolution: v1.9.4-BETA
 - [Modpack](https://drive.google.com/file/d/16QtstSeUdYxpprMlMIkkwfht3RhtWbI9/view?usp=sharing)

**Comment by GabrielOlvH** [comment]
This should be already fixed in the latest version of the mod. Please test it with the latest version and reopen the issue if it still exists.
