### ISSUE TITLE
[SUGGESTION] Upgradable cabinets 

### ISSUE THREAD

**Issue by MCrafterzz** [GabrielOlvH/Industrial-Revolution#179]
**Description:**
It would be cool if cabinets could be upgraded like most of the machines. Higher upgrades would have larger storage space similarly to extended storage, would make them more useful than a vanilla barell. Maybe there could be two different upgrades, slot upgrades for more slots and count upgrades for larger stack sizes. So you would have to prioritize as you would only be able to have 4 upgrades just like the machines

**Reason:**
- Cabinets feel quite useless rn. You can't even configure the input/output sides

**Comment by GabrielOlvH** [comment]
The cabinet mainly a decoration storage block that matches the look of the mod. More storage options will be included in the [Dynamic Storage Addon](https://github.com/GabrielOlvH/Industrial-Revolution-Dynamic-Storage)
