### ISSUE TITLE
The book says Laser Emitter store 25M, they store 2,5M [BUG] 

### ISSUE THREAD

**Issue by henkaa** [GabrielOlvH/Industrial-Revolution#187]
**Description:**
In the ingame book, it says that the Laser Emitter can store up to 25M LF, but it only seems to store up to 2,5M LF. Is this a bug, or is this maybe a feature that the modpack has made in altering in the config?

Anyhow. 2,5M seems a bit wrong, since that kind of implies that you need to build 10 MK4 Flux Containers to store that 100M you need per Core.. and that is ALOT of resources, just to make the 4 cores you need to the armor.

**Steps to Reproduce:**
Build the Laser Emitter and prove that it only stores 2,5M (or look at the info in REI). Look in the book and it say 25M.

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.34.2
 - Industrial Revolution: 1.9.12-BETA
 - Modpack: All of Fabric 3-2.7.4

**Logs:**
N/A

**Details:**
N/A

**Comment by GabrielOlvH** [comment]
It's a typo in the book, it is 2,5M. It is intended to be expensive since it's a powerful endgame armor. More ways of generating energy will be added in later updates

**Comment by GabrielOlvH** [comment]
Didn't mean to close it, didn't fix the typo yet
