### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by derram** [GabrielOlvH/Industrial-Revolution#206]
**Description:**
Chopper mines out two blocks beyond "show range" area, though it does not replant saplings past the marked area.

**Steps to Reproduce:**
- Set range, place logs up to two blocks outside of marked area. 

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: fabric-api-0.34.2+1.16
 - Industrial Revolution:  v1.9.12-BETA
 - Modpack:  All Of Fabric 3 -2.7.4

**Logs:**
- N/A

**Details:**
![2021-05-25_10 35 23](https://user-images.githubusercontent.com/5730335/119527527-038f1080-bd46-11eb-9fcb-3da0867b4c0f.png)

**Comment by MCrafterzz** [comment]
I think this is intended as some modded trees grow outwards

**Comment by derram** [comment]
The problem is it happens with placed blocks as well.

**Comment by GabrielOlvH** [comment]
This is intended, it harvests in a slightly larger range than it plants. I am aware it's not a good solution, it will be reworked in the future.

**Comment by GabrielOlvH** [comment]
This was fixed by 5dce4c94968fd2029203b6f223f376a100c6542d
