### ISSUE TITLE
How is the miner supposed to work?

### ISSUE THREAD

**Issue by Luro02** [GabrielOlvH/Industrial-Revolution#21]
I am playing the modpack `All of Fabric 3`, which uses Industrial Revolution `v.1.4.7-BETA`.

I connected the `Miner` to a `Solar Panel` and scanned the chunk by holding right click until I got the `Scan Output`. I then put the `Scan Output` inside the `Miner` and it started mining, after it finished I have the following in my chest:
![Screenshot_20200805_152300](https://user-images.githubusercontent.com/24826124/89417903-9fa44880-d72f-11ea-8386-3f6b108083b8.png)

Is this the correct output? It did not mine any iron, gold, lapis, diamond or redstone ore. (It also did not mine ores from other mods, like TechReborn).

**Comment by GabrielOlvH** [comment]
Each chunk has it's own vein type which define what type of ores can be found. You can read the vein type by hovering the Scan Output and you can use the Guide Book (Industrial Revolution) to know which ores can be found there. More veins will be added at some point and the vein sizes will be greatly increased in the next update. 
Now that the miner has finished in that chunk, you have to scan a different one and move your miner. If you have any other issues please let me know!

**Comment by Luro02** [comment]
Thank you for the kind and fast response :)

**Comment by Adirelle** [comment]
> Each chunk has it's own vein type which define what type of ores can be found.

Is this different from what can actually be found by digging the chunk ? Said otherwise: does the miner dig the existing ores, or does it "create" ores according to the scan report ?

**Comment by GabrielOlvH** [comment]
It creates ores according to the scan report
