### ISSUE TITLE
[REQUEST] Autocrafter

### ISSUE THREAD

**Issue by Friedboss** [GabrielOlvH/Industrial-Revolution#211]
Autocrafter
With the autocrafter you could craft items automaticly like the crafting table at a cost of energy.

**Reason:**
I could make a real factory where you produce something.

**Comment by MCrafterzz** [comment]
Gabriel said that it'll be part of the storage addon: https://github.com/GabrielOlvH/Industrial-Revolution-Dynamic-Storage

**Comment by GabrielOlvH** [comment]
Thanks for the suggestion, but I'll close this as it will be part of the storage addon.
