### ISSUE TITLE
[BUG] Rendering of modular armor inside of the modular workbench is totally broken

### ISSUE THREAD

**Issue by MCrafterzz** [GabrielOlvH/Industrial-Revolution#219]
![image](https://user-images.githubusercontent.com/19669673/119681632-885f5480-be42-11eb-8bf3-e606a4a7cea1.png)

**Comment by RemagOfficial** [comment]
probably a sodium thing if you have it

**Comment by MCrafterzz** [comment]
I don't think AOF3 has Sodium

**Comment by MCrafterzz** [comment]
Tested with only Indrev and this does not happen, maybe one of the mods in AOF3 bundles Sodium?
