### ISSUE TITLE
[BUG] stained glass makes cables invisible

### ISSUE THREAD

**Issue by Matthew-Bates** [GabrielOlvH/Industrial-Revolution#223]
when looking at cables through stained glass the texture is bugged and If the cable has a block placed inside of it like a facade it is entirely invisible.

https://imgur.com/a/8aZzmv0

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.34.2
 - Industrial Revolution: 1.9.15
 - Modpack: all of fabric 3

**Comment by GabrielOlvH** [comment]
![image](https://user-images.githubusercontent.com/17054373/119869168-4d1e5d80-bef6-11eb-8cc3-e617d5cf6e5a.png)
Cannot reproduce. Are you using mods like Indium/Sodium/Canvas/Optifine?

**Comment by GabrielOlvH** [comment]
Wait ignore me i'm stupid

**Comment by GabrielOlvH** [comment]
![image](https://user-images.githubusercontent.com/17054373/119869544-bdc57a00-bef6-11eb-8d23-45fca6f6a612.png)
oh well still cannot reproduce

**Comment by hugeblank** [comment]
Not sure if AOF3 has canvas, but I'm experiencing the above with it - among other culling weirdness.
![image](https://user-images.githubusercontent.com/16393543/120466900-70149b80-c354-11eb-92bf-6e5acce34ca4.png)

**Comment by GabrielOlvH** [comment]
Closing this since I cannot reproduce and it's been inactive for a while. If this still happens in 1.17 please reopen the issue.
