### ISSUE TITLE
[REQUEST] Make the miner continue to mine non-ores even after the vein has ran out

### ISSUE THREAD

**Issue by MCrafterzz** [GabrielOlvH/Industrial-Revolution#224]
This would makes blocks such as stone, dirt and soul sand fully automatic and renewable without creating infinite ores. All makes sense as the world contains a lot of stone and a vain is only a part of it.

**Comment by Friedboss** [comment]
It could be that you dont mine really fast but forever even the ores with an autocrafter in the storage update you could automize almost evrything.

**Comment by GabrielOlvH** [comment]
Added as of 1.10.0-beta.1
