### ISSUE TITLE
modular helmet bug[BUG] 

### ISSUE THREAD

**Issue by Akira-Kyu** [GabrielOlvH/Industrial-Revolution#236]
**Description:**
After crafting and installing all the modules on the modular helmet i equipped it and tha game crashed and now everytime i load in to the world it crash again

**Steps to Reproduce:**
install all possible module on modular helmet ad equip it

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.34.2
 - Industrial Revolution: 1.9.17
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.
[crash-2021-06-09_00.59.55-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/6620096/crash-2021-06-09_00.59.55-client.txt)

**Comment by GabrielOlvH** [comment]
Seems to be unrelated to Industrial Revolution and caused by VoxelMap.

**Comment by Akira-Kyu** [comment]
> Seems to be unrelated to Industrial Revolution and caused by VoxelMap.

oh ty so much, sorry for bothering
