### ISSUE TITLE
[BUG] Mining rig drill heads with unbreaking enchant

### ISSUE THREAD

**Issue by Danklor** [GabrielOlvH/Industrial-Revolution#237]
Indrev 1.9.17-beta
MC 1.16.5
Fabric loader 0.11.3, API 0.35.0+1.16
Many other mods, but likely not a factor

A mining rig drill head can have the unbreaking enchantment applied from a book at an anvil. When this drill head is used the durability goes down every operation indicating the unbreaking has no effect.  I would expect either the drill heads to not accept enchantments at all or that the applied enchantments would work.

**Comment by TheLostInPlace** [comment]
> durability goes down every operation

Unbreaking does not mean unbreakable if the enchant used here is vanilla Minecraft unbreaking. What level of unbreaking was it? Also, did you notice if the durability CONSISTENTLY ticked down, even with unbreaking? If so then yea, the enchant is being ignored. Usually unbreaking does a (level+1) modifier, meaning if it has Unbreaking I, the "head" will last 2x as long. [Unbreaking Wiki](https://minecraft.fandom.com/wiki/Unbreaking)

**Comment by Danklor** [comment]
I tried with unbreaking III and durability was constantly used in every single mining operation.  Therefore the drill head broke in the same amount of time it would have without any enchantment.
