### ISSUE TITLE
[BUG] crash on startup

### ISSUE THREAD

**Issue by TheNimbleNinja** [GabrielOlvH/Industrial-Revolution#239]
**Description:**
crash on startup
**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.11.5
 - Industrial Revolution: Industrial Revolution 1.10.0-alpha.1
 - Modpack: mine

**Logs:**
https://gist.github.com/TheNimbleNinja/b83c441734457af34a92494dee0ff131
**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
That crash doesn't seem to have nothing to do with Industrial Revolution, report to VoxelMap.
