### ISSUE TITLE
[BUG] Raw tin,silver,lead 

### ISSUE THREAD

**Issue by grain12** [GabrielOlvH/Industrial-Revolution#240]
Description:
- Minecraft version 1.17 drops when mining ore raw tin,lead,silver cannot be melted in the furnace

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.11.6
 - Industrial Revolution: 1.10.0-alpha.2
 - Modpack: All of Fabric 4 - 1.17

**Comment by GabrielOlvH** [comment]
Make sure you have correctly updated because those recipes exist since alpha 2. If the issue persists open another issue with screenshots.
