### ISSUE TITLE
indrev-1.10.0-alpha.4.jar conflict when start up 

### ISSUE THREAD

**Issue by larry010129** [GabrielOlvH/Industrial-Revolution#244]
when starting the game there are conflict with other mods 

for example:
______________________________________________
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
______________________________________________

**Comment by GabrielOlvH** [comment]
Please open a new issue and fill out the form correctly. This message tells me nothing, at least attach the full logs.
