### ISSUE TITLE
[BUG] Slaughter block crashes the game/server

### ISSUE THREAD

**Issue by Pretender8** [GabrielOlvH/Industrial-Revolution#249]
**Description:**
- When placed and powered, the Slaughter block crashes the game/server. 

**Steps to Reproduce:**
- Make a new world
- Place a slaughter and a power source (used creative Lazuli Flux Container)
- World should crash in a few seconds of it being active
**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.36.0
 - Industrial Revolution: 1.10.0-alpha.5
 - Modpack: Custom, see logs

**Logs:**
https://gist.githubusercontent.com/natanfudge/dffc0f78b6b5905b5517a6aeb95a727b/raw/ef6854a0892ff418b79be2ed2069e1f432ea28d9/crash.txt

**Details:**
![image](https://user-images.githubusercontent.com/34997550/123335232-c915c080-d509-11eb-8a9a-0e505b214bfd.png)
![image](https://user-images.githubusercontent.com/34997550/123335331-eba7d980-d509-11eb-8587-0f0aebec0f11.png)

**Comment by GabrielOlvH** [comment]
It's an incompatibility with one of the mods, specifically ``ne-v-seti: Ne v seti 0.1.5-1.17-pre1``. This will crash with any fake players from any mod, they have to fix it on their end.

**Comment by Pretender8** [comment]
If I may ask, where is ne-v-seti used? I don't see it in the modlist.
