### ISSUE TITLE
[BUG] raw ores don't smelt in industrial smelter

### ISSUE THREAD

**Issue by nikolapintaric** [GabrielOlvH/Industrial-Revolution#250]
**Description:**
- raw ores don't work in industrial smelter

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.36.0
 - Industrial Revolution: 1.10.0-alpha7
 - Modpack: [mod list](https://pastebin.com/D1kUDQn1)

**Details:**
![iron](https://user-images.githubusercontent.com/3183808/123820644-436b8980-d8ea-11eb-952c-55f920d785c4.png)
![lead](https://user-images.githubusercontent.com/3183808/123820717-51b9a580-d8ea-11eb-9ccd-c48aff7ca2a1.png)

**Comment by GabrielOlvH** [comment]
It's not a bug, you need the ore block to melt it
