### ISSUE TITLE
[BUG] Solid Infuser REI Steel Dust recipe error

### ISSUE THREAD

**Issue by SiongSng** [GabrielOlvH/Industrial-Revolution#252]
**Description:**
To make Steel Dust, it should be coal dust + iron dust, but this is not shown in the recipe 

**Steps to Reproduce:**
- Open the Steel Dust REI recipe GUI

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.36.0
 - Industrial Revolution: 1.10.0-alpha.7
 
![image](https://user-images.githubusercontent.com/48402225/124260169-f1cd3400-db61-11eb-8875-9b0424d32ff6.png)

**Comment by GabrielOlvH** [comment]
What's the bug?

**Comment by SiongSng** [comment]
The recipe displayed in REI is coal dust (TechReborn) + coal dust (Industrial-Revolution), but it should be coal dust + iron dust in order to make it.

**Comment by GabrielOlvH** [comment]
This is fixed as of alpha 12. Thanks for reporting.
