### ISSUE TITLE
[BUG] Missing Textures

### ISSUE THREAD

**Issue by Angelic-System** [GabrielOlvH/Industrial-Revolution#253]
**Description:**
- Give a detailed explanation of the issue
The Mod Has alot of missing textures
**Steps to Reproduce:**
- Steps to reproduce this behaviour
Go in REI and look for the items and find Missing textures
**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.11.6
 - Industrial Revolution: V1.10.0-Alpha.7
 - Modpack: Custom

**Logs:**
- Use a paste service, do not paste the logs directly here.
n/a
**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.
![image](https://user-images.githubusercontent.com/45043402/124355062-92c5f880-dc0f-11eb-8e29-3dc49a7d25b7.png)

**Comment by RemagOfficial** [comment]
do you have sodium?

**Comment by Angelic-System** [comment]
yes

**Comment by RemagOfficial** [comment]
then remove it, that's why there's missing textures

**Comment by Angelic-System** [comment]
how the hell does sodium cause missing textures?????

**Comment by Angelic-System** [comment]
Fixed By using indium for sodium
