### ISSUE TITLE
[BUG] 1.17 chopper not working w pipes or hopper

### ISSUE THREAD

**Issue by Knito58** [GabrielOlvH/Industrial-Revolution#254]
**Description:**
Trying to get a chopper to work automagically. The chopper MK1 w/o any updates workes nicely. It produces oak logs, sticks and apples. I want to pipe the products out to make charcoal and put the other things away. But it won't give anything out. Even a dull hopper placed below won't be able to pull someting out of the chopper's output area. Only accessing it by bare and freshly washed hands gets that logs out.

**Steps to Reproduce:**
Try to get st out of the chopper with indrev servoed pipes.
That pipes work fine with chests alone.  I read the guide, set up connected chests to understand the piping system. Pulling filtered content from left chest to right chest just works fine.
But the chopper seems to hate pipes, servos and hoppers.

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: 0.36.0 1.17
 - Industrial Revolution: 1.10.0 alpha 7
 - Modpack: none

I'm doing st wrongly, isn't it?

**Comment by GabrielOlvH** [comment]
You need to configure machines input and output using a Wrench.

**Comment by Knito58** [comment]
Thank you. Seems to work.
