### ISSUE TITLE
[REQUEST] Nikolite block

### ISSUE THREAD

**Issue by CanINotUseTruth** [GabrielOlvH/Industrial-Revolution#257]
**Description:**
- The ability to craft a nikolite block from nikolite dust, in the same way redstone dust works.

**Reason:**
- Once a player has fortune long mining trips present an inventory space issue, compressing the nikolite into blocks would allow relief for some of that issue.
- This is similar to all the raw ore blocks as well.

**Comment by GabrielOlvH** [comment]
Duplicate for #133
