### ISSUE TITLE
Cant make purified iron

### ISSUE THREAD

**Issue by thereal123dprinter** [GabrielOlvH/Industrial-Revolution#259]
I have a fluid infuser set up with sulfuric acid, but if I place raw iron into it, it wont purify it.

**Steps to Reproduce:**
Just try and purify some iron.

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: [1.17-pre1/2/3/4/5/rc1/2] Fabric API 0.34.8
 - Industrial Revolution: Industrial Revolution 1.10.0-alpha.7
 - Modpack: Modified AOF 6

**Logs:**
N/A

**Details:**
![image](https://user-images.githubusercontent.com/73493250/124943292-fbc3bc80-dfd1-11eb-8391-4916e0f94320.png)

**Comment by Footage2-Amply-Pounce** [comment]
Not a bug. You dont purify raw ores, you can only pulverize it. Purification works with ore blocks, which you can collect with silk touch. 

Note that diamond, emerald, coal, lapis lazuli and redstone can not be smelted at all.

**Comment by GabrielOlvH** [comment]
As already stated above, this is not a bug.
