### ISSUE TITLE
[BUG] Failing to launch after alpha8

### ISSUE THREAD

**Issue by kamodius** [GabrielOlvH/Industrial-Revolution#260]
**Description:**
- Minecraft fails to launch after updating to 1.10.alpha.8
**Steps to Reproduce:**
- Update from 1.10.alpha.7 to 1.10.alpha.8

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: fabri-api-0.36.0+1.17
 - Industrial Revolution: 1.10.0-alpha.8
 - Modpack: n/a

**Logs:**
- A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: indrev requires {libgui @ [*]}

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
Update to minecraft 1.17.1

**Comment by kamodius** [comment]
Well don't I feel stupid.  Didn't notice 1.17.1 hit release.  My apologies.
