### ISSUE TITLE
[BUG] Selecting the wrench/config tab of a Rancher causes a crash

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#262]
**Description:**
- While right clicking a Rancher machine and then opening its config tab (the wrench icon) causes an instant crash. 

**Steps to Reproduce:**
- Craft/spawn and place down a Rancher (MK4 in my case, but probably affects all of them), right click on it, then left click on the wrench icon.

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.36.1
 - Industrial Revolution: 1.10.0 alpha 8
 - Modpack: custom, modlist provided in the crash log

**Logs:**
- [crash-2021-07-10_14.48.14-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/6795313/crash-2021-07-10_14.48.14-client.txt)

**Details:**
Technical information about my PC is also available in the crash log. I can not recall if there are other machines that have the wrench tab, but if there are, I would assume that all of them are affected, not just the Rancher.

**Comment by GabrielOlvH** [comment]
I can't seem to reproduce this, can you test with just Industrial Revolution?

**Comment by SplendidAlakey** [comment]
Yes, just tested it with only fabric-api-0.36.1+1.17, fabric-language-kotlin-1.6.2+kotlin.1.5.20 and indrev-1.10.0-alpha.8 loaded. Created an entirely new world, no extra data packs, creative, put down a Rancher MK4, right clicked it, then left clicked on the wrench and crashed. 

Crash log: [removed]


This was MC launcher's crash message:

> The game crashed whilst mousereleased event handler
Error: java.lang.IllegalAccessError: Update to non-static final field io.github.cottonmc.cotton.gui.ValidatedSlot.field_7873 attempted from a different class (io.github.cottonmc.cotton.gui.ValidatedSlot) than the field's declaring class
Exit Code: -1
