### ISSUE TITLE
[BUG] java.lang.IllegalAccessError opening modular workbench in 1.10.0-alpha.8

### ISSUE THREAD

**Issue by Danklor** [GabrielOlvH/Industrial-Revolution#263]
When attempting to open a modular workbench the game immediately crashes with an
java.lang.IllegalAccessError: Update to non-static final field io.github.cottonmc.cotton.gui.ValidatedSlot.field_7873 attempted from a different class (io.github.cottonmc.cotton.gui.ValidatedSlot) than the field's declaring class
	at io.github.cottonmc.cotton.gui.ValidatedSlot.setVisible(ValidatedSlot.java:175) ~[LibGui-4.1.3+1.17.1.jar:?]

MC 1.17.1 & Fabric API 0.36.1+1.17
I tried both LibGUI 4.1.2 and 4.1.3 with the same result.

All details in attached log file

[indrev-libgui-workbench-crash.log](https://github.com/GabrielOlvH/Industrial-Revolution/files/6796797/indrev-libgui-workbench-crash.log)

**Comment by GabrielOlvH** [comment]
I can't seem to reproduce this, can you test with just Industrial Revolution?

**Comment by Danklor** [comment]
I tried with only Industrial Revolution and it's requirements, but still get the crash. Log attached.

[indrev-libgui-workbench-crash2.log](https://github.com/GabrielOlvH/Industrial-Revolution/files/6797335/indrev-libgui-workbench-crash2.log)
