### ISSUE TITLE
[BUG] Setting correct inputs/outputs for the energy flow after connecting machines does not allow for the energy to transfer

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#266]
**Description:**

Connecting machines and a Lazuli Flux container *before* selecting correct inputs/outputs with a Wrench will prevent power from transferring between them, even if you select proper settings *afterwards*. Easier to reproduce while using cables, but having machines next to each other also produces the same results.

**Steps to Reproduce:**

1. Place down a Lazuli Flux container (MK4 in my case)
2. Place down a power generator or a Lazuli Flux container Creative at least 1 block away from a non-creative container
3. Use a Wrench to set the non-creative container to have outputs in all directions; use a Wrench to set the creative container/power generator to have outputs in all directions too
4. Use a Cable (MK4 in my case) to connect both containers

Expected result: power does not transfer, however, using a Wrench to set a proper input side for the non-creative container allows the energy to transfer.

Actual result: power does not transfer, however, using a Wrench to set a proper input side for the non-creative container does not allow the energy to transfer.

Temporary fix: remove the cables, properly set up the machine's power inputs and outputs first and only then connect them with cables.

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.37.0
 - Industrial Revolution: 1.10.0-alpha.9
 - Modpack: custom
 
 <details>
  <summary>Mod list</summary>

[1.17]+Magic+Mirror+1.3.1
Adorn-2.1.1+1.17.1-fabric
advancements-enlarger-0.2.4
amecs-1.3.4+mc.1.17
appleskin-fabric-mc1.17-2.0.0
architects-palette-fabric-port-1.2
architectury-2.2.21-fabric
Artificial_Foliage_1.7_(FABRIC)_1.17-1.17.1
attachleadstologs-1.0.0-1.17.1
artisanat-2.1
autoconfig1u-3.3.1
axolotl-item-fix-1.1.1
backslot-1.1.13
backslotaddon-1.0.4
bclib-0.2.3
bedrockify-1.1.1+mc1.17
beehive-tooltips-1.3.0
beenfo-1.17.1-fabric0.36.1-1.3.2
betterbeds-1.2.0
BetterControls-1.17+-v1.2.0
better-end-0.10.5-pre
BetterMineshafts-Fabric-1.17-1.0.0
BetterStrongholds-Fabric-1.17-1.1
better-wandering-trader-1.7.0
bigbeacons-1.2.3
blockus-2.2.6+1.17.1
branders-sulfurpotassiummod-1.17-1.1.1
BuildingWands-Fabric_1.17.1-1.5_beta2
Cardinal-Components-API-3.0.1
carpet-extra-1.17.1-1.4.43
carpet-tis-addition-mc1.17.1-1.20.0+build.633
carrier-1.8.0
cavebiomes-0.6.3
charm-fabric-1.17-3.3.0
charmonium-fabric-1.17-3.3.0
clayrecipefabric-2.0.0
cleardespawn-1.17.1-fabric0.36.1-1.1.1
clientsidenoteblocks-2.0+1.17
cloth-api-2.0.54
cloth-config-5.0.34-fabric
Clumps-fabric-1.17-7.0.0.2
comforts-fabric-0.0.4-1.17
consistency_plus-1.17-0.4.0-RC1
CraftPresence-Fabric-1.17.1-Release-1.8.2
Croptopia-1.17-FABRIC-1.5.0
custom-portals-2.1.0
DarkPaintings-fabric-1.17-3.0.6
dawn-2.0.3
dazzle-2-1.17-1.0
death_controls-1.1.0
DisableCustomWorldsAdvice-1.3
dragonloot-1.0.8
DualRiders-1.17-1.0.5
Dynocaps-1.8.1
Earth2Java-1.7.1+1.17
elementalcreepers-1.4.0
EnchantmentDescriptions-fabric-1.17-3.0.12
expandedstorage-7.0.0-alpha.33+1.17
fabric-api-0.37.0+1.17
fabric-carpet-1.17.1-1.4.44+v210714
fabric-enchantments-0.3.2
fabric-language-kotlin-1.6.2+kotlin.1.5.20
fabric-searchable-containers-1.17.1-1.3.0
fabrilous-updater-2.3
fallingleaves-1.7.2+1.17
FallingTree-1.17.1-2.12.1
fast-chest-1.2+1.17
ferritecore-3.0.1-fabric
flytre_lib-1.17-0.2.21
forgottenrecipes-fabric-1.0.1
goosiks-villager-hats-mc1.17-1.2.0
grid-1.17.1-fabric0.36.1-1.6.5
grizzlybear-1.1.1
helpwanted-1.1.0
horse-stats-vanilla-4.1.8
image2map-0.2.1
indrev-1.10.0-alpha.9
inmis-2.3.1-1.17
InventoryHUD-fabric-[1.17]-3.3.2
InventorySorter-1.7.9-1.17
invisiblights-fabric-7.1+1.17
itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506
Lakeside-1.1.0+1.17
lapisreserve-1.0.8
lazydfu-0.1.2
lifts-1.2-BETA+1.17
linkedstorage-1.3.11-1.17
lovely_snails-1.0.2+1.17
malilib-fabric-1.17.1-0.10.0-dev.24
mcda-1.7.5
mcdar-1.3.1
mcdw-3.2.4
mcsa-2.3.2-1.17
megane-5.1.1
modmenu-2.0.2
morevillagers-FABRIC-1.17-2.0.3
netherite-items-1.17-1.1.0
notenoughcrashes-3.3.1+1.17-fabric
offhandoverhaul-1.1.1
onsoulfire-1.17-2
optifabric-1.11.18
Paxi-Fabric-1.17-1.2
pettable-1.2.0
PlayerPig-2.1
pling-1.4.0
PresenceFootsteps-r31-1.17-rc1
preview_OptiFine_1.17.1_HD_U_G9_pre29
replanter-fabric-1.17.1-1.3
repurposed_structures_fabric-2.1.1+1.17.1
respawnablepets-1.17-2
RoughlyEnoughItems-6.0.264-alpha-fabric
rug-1.17.1-1.1.12
scorch-1.0.2
secretrooms-1.0.0+1.17
shulkerboxtooltip-3.0.0+1.17
sihywtcamc-1.3.1+1.17.1
sihywtcamd-1.3.1+1.17.1
SimpleBackpack_Fabric-1.17.1-1.1.13
soundphysics-2.0.0
speedyhopper-1.1-1.17-1
statuseffecttimer-1.0.3
stickyhopper-2.3-1.17-1
stitched-snow-1.0.3
terrarian-slimes-1.1-BETA+1.17
tomsstorage-1.1.13-1.17.1
trident_revision-1.0.2
trinkets-3.0.2
true-secret-rooms-1.1.4
TweakMyClient-fabric-mc1.17-1.1.6+build.22
twigs-1.0.1
vanillaplusbiomes-0.3.2
veinmining-fabric-0.0.10-1.17
villagernames-1.17-2.0.0
voicechat-fabric-1.17.1-1.0.6
Walkways-1.0.1
wanderingcollector-1.0.2+mc1.17
whereisit-1.17.1-1.13.1
wirelessnetworks-1.1.2
witherite-0.0.8-hotfix
wraith-silkspawners-1.0.2
wthit-fabric-3.7.0
Xaeros_Minimap_21.13.0_Fabric_1.17.1
XaerosWorldMap_1.14.6.1_Fabric_1.17.1
xlpackets-2.0-1.17
YungsApi-1.17-Fabric-13
</details>

On a side note, some GUI elements do not refresh properly since alpha8. For example, when you install a Buffer enhancer on a machine: 
![2021-07-18_12 39 36](https://user-images.githubusercontent.com/86702831/126064496-c205e8e4-7b9c-4e45-b71b-38dbfb58a8b2.png)

Did not feel like it was worth making a whole new thread for it.

**Comment by douglasg14b** [comment]
This still appears to be a problem. I had to break cables to get machine to connect after adjusting sides.
