### ISSUE TITLE
Crash with item pipe [BUG] 

### ISSUE THREAD

**Issue by renzhentaxi** [GabrielOlvH/Industrial-Revolution#267]
**Description:**
Crash with pipe

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.17
 - Fabric API: fabric: Fabric API 0.37.0+1.17
 - Industrial Revolution: Industrial Revolution 1.10.0-alpha.1
 - Modpack: All of Fabric

**Logs:**
https://pastebin.com/Pj9s8tRv
**Details:**

I think the issue is with the random mode https://github.com/GabrielOlvH/Industrial-Revolution/blob/3939a65cb2d0746f4b86dd7c0e11a5c0283d3f26/src/main/kotlin/me/steven/indrev/networks/EndpointData.kt#L97.

Timsort requires that `a > b` and `b > c` then `a > c` but it looks like the comparator for random mode is returning -1,0,1 randomly everytime. Which means that sometimes it might cause the following to be true `a>b` `b>c` and `c>a`

Might also be the round robin mode bugging (maybe some types of race condition where the inventory got updated while the sorting was happening)

**Comment by GabrielOlvH** [comment]
Thanks for the detailed report, it made fixing it much easier :)
