### ISSUE TITLE
[BUG] pipes ,cables and other industrial blocks missing textures in newest 1.16.5 version

### ISSUE THREAD

**Issue by sa1672ndo** [GabrielOlvH/Industrial-Revolution#269]
**Description:**
- all industrial blocks and pipes with cables are missing textures

**Steps to Reproduce:**
- no idea

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.37.0+1.16
 - Industrial Revolution: 1.9.18
 - Modpack: campanion 1.3.5, fabric kotlin 1.6.1+kotlin.1.5.10 , go fish 1.2.3

**Logs:**
- 

**Details:**
![image](https://user-images.githubusercontent.com/87911255/126877604-70beff77-26fe-4f91-aeb7-034fba33a09b.png)

**Comment by Moocow9m** [comment]
I have the same issue in 1.17.1

**Comment by sa1672ndo** [comment]
fixed it by removing sodium

**Comment by Footage2-Amply-Pounce** [comment]
If you use Sodium, you have to use Indium for some fabric mods to render properly.
