### ISSUE TITLE
Display issue: Modular Workbench

### ISSUE THREAD

**Issue by Katorone** [GabrielOlvH/Industrial-Revolution#27]
![image](https://user-images.githubusercontent.com/918422/90431428-55c14800-e0c9-11ea-902d-f34d336827da.png)

I don't know if this is a REI issue.  If it is, please let me know and I'll report it there instead.

Edit: Sorry, I forgot to include some information.
MC 1.16.2
IndRev: indrev-1.5.1-BETA.jar
The same display issue appears on the flux containers

**Comment by GabrielOlvH** [comment]
That was my mistake, it happens for every machine that does not have a config entry (it's only visual, the machine works fine). I'll fix it for the next update, thank you for reporting.

**Comment by Katorone** [comment]
Thanks!  Love your mod. :-D

**Comment by GabrielOlvH** [comment]
This should be fixed as of 1.6.0-BETA which you can download [https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3043918](here). Thanks for the report!
