### ISSUE TITLE
[BUG] Mining drill possibly causing a crash when mining a lot if a Silk touch module is installed

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#270]
**Description:**

I have a modular mining drill with 5 efficiency modules, 1 range module and 1 silk touch module. When mining non-stop with that drill, whoever is doing it encounters a crash. I have a few more modular mining drills with identical modules installed minus silk touch, and using those drills does not cause a crash.

**Steps to Reproduce:**

1. Get a modular drill
2. Install: 5 efficiency upgrades, 1 range upgrade, 1 silk touch upgrade
3. Start mining non-stop

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: 0.37.1
 - Industrial Revolution: indrev-1.10.0-alpha.11
 - Modpack: custom
 
 <details>
  <summary>Mod list</summary>

[1.17]+Magic+Mirror+1.3.2
Adorn-2.1.1+1.17.1-fabric
advancements-enlarger-0.2.4
amecs-1.3.4+mc.1.17
appleskin-fabric-mc1.17-2.0.0
architects-palette-fabric-port-1.2
architectury-2.2.21-fabric
Artificial_Foliage_1.7_(FABRIC)_1.17-1.17.1
attachleadstologs-1.0.0-1.17.1
artisanat-2.1
autoconfig1u-3.3.1
axolotl-item-fix-1.1.1
backslot-1.2.0
backslotaddon-1.0.5
bclib-0.2.4
bedrockify-1.1.1+mc1.17
beehive-tooltips-1.3.0
beenfo-1.17.1-fabric0.36.1-1.3.2
betterbeds-1.2.0
BetterControls-1.17+-v1.2.0
better-end-0.10.5-pre
betterf3-1.1.5+1.17
BetterMineshafts-Fabric-1.17-1.0.0
BetterPingDisplay-Fabric-1.17.1-1.1
BetterStrongholds-Fabric-1.17-1.1
better-wandering-trader-1.7.0
bigbeacons-1.2.3
blockus-2.2.7+1.17.1
branders-sulfurpotassiummod-1.17-1.1.1
BuildingWands-Fabric_1.17.1-1.5_beta2
Cardinal-Components-API-3.1.1
carpet-extra-1.17.1-1.4.43
carpet-tis-addition-mc1.17.1-1.20.0+build.633
carrier-1.8.0
cavebiomes-0.6.3
charm-fabric-1.17-3.3.2
charmonium-fabric-1.17-3.3.0
clayrecipefabric-2.0.0
cleardespawn-1.17.1-fabric0.36.1-1.1.1
clear-skies-mc117-1.5.70
clientsidenoteblocks-2.0+1.17
cloth-api-2.0.54
cloth-config-5.0.34-fabric
Clumps-fabric-1.17-7.0.0.2
comforts-fabric-0.0.4-1.17
compostable-rottenflesh-1.0.0
consistency_plus-1.17-0.4.0-RC1
CraftPresence-Fabric-1.17.1-Release-1.8.2
Croptopia-1.17-FABRIC-1.5.0
custom-portals-2.1.0
DarkPaintings-fabric-1.17-3.0.6
dawn-2.0.3
death_controls-1.1.0
DisableCustomWorldsAdvice-1.3
dragonloot-1.0.8
DualRiders-1.17-1.0.5
Dynocaps-1.8.1
Earth2Java-1.7.1+1.17
elementalcreepers-1.4.0
EnchantmentDescriptions-fabric-1.17-3.0.12
expandedstorage-7.0.0-alpha.33+1.17
fabric-api-0.37.1+1.17
fabric-carpet-1.17.1-1.4.44+v210714
fabric-enchantments-0.3.2
fabric-language-kotlin-1.6.3+kotlin.1.5.21
fabric-searchable-containers-1.17.1-1.3.0
fabrilous-updater-2.3
fallingleaves-1.7.2+1.17
FallingTree-1.17.1-2.12.1
fast-chest-1.2+1.17
ferritecore-3.0.1-fabric
flytre_lib-1.17-0.2.21
forgottenrecipes-fabric-1.0.1
goosiks-villager-hats-mc1.17-1.2.0
grid-1.17.1-fabric0.36.1-1.6.5
grizzlybear-1.1.1
helpwanted-1.1.0
horse-stats-vanilla-4.1.8
hydrogen-fabric-mc1.17.1-0.3
illuminations-1.6.1
image2map-0.2.1
indium-1.0.0+mc1.17.1
indrev-1.10.0-alpha.11
inmis-2.3.1-1.17
inventory-control-tweaks-1.3.8+MC1.17-1.17.1
InventoryHUD-fabric-[1.17]-3.3.2
InventoryProfilesNext-fabric-1.17-0.8.4
invisiblights-fabric-7.1+1.17
krypton-0.1.4
Lakeside-1.1.0+1.17
lambdabettergrass-1.2.0+1.17
lambdynamiclights-2.0.1+1.17
lapisreserve-1.0.8
lazydfu-0.1.2
lifts-1.2-BETA+1.17
linkedstorage-1.3.11-1.17
lithium-fabric-mc1.17.1-0.7.3
lovely_snails-1.0.2+1.17
malilib-fabric-1.17.1-0.10.0-dev.24
mcda-1.7.5
mcdar-1.3.1
mcdw-3.3.4
mcsa-2.3.2-1.17
megane-5.1.1
milk_plus-1.1.0
minegate-moreblocks-1.1.6
minitweaks-1.1.1
MobCatcher-Fabric-1.17.1-1.0.6
modmenu-2.0.4
MoreFlowerPots-2.0-SNAPSHOT
morevillagers-FABRIC-1.17-2.0.4
mousewheelie-1.7.3-newconfig.2+mc1.17.1-pre1
netherite-items-1.17-1.1.0
notenoughcrashes-3.4.0+1.17-fabric
offhandoverhaul-1.1.1
onsoulfire-1.17-2
paradox-slabs-0.1.1
Paxi-Fabric-1.17-1.2
PlayerPig-2.1
pling-1.4.0
ppp-1.17.1-1.2.2
PresenceFootsteps-r31-1.17-rc1
repurposed_structures_fabric-2.1.2+1.17.1
respawnablepets-1.17-2
RoughlyEnoughItems-6.0.264-alpha-fabric
rug-1.17.1-1.1.12
scorch-1.0.2
searchlight-1.17-fabric-1.1.1
secretrooms-1.0.0+1.17
shulkerboxtooltip-3.0.0+1.17
sihywtcamc-1.3.1+1.17.1
sihywtcamd-1.3.1+1.17.1
SimpleBackpack_Fabric-1.17.1-1.1.13
sodium-extra-mc1.17.1-0.3.3
sodium-fabric-mc1.17.1-0.3.0+build.5
soundphysics-2.0.0
speedyhopper-1.1-1.17-1
statuseffecttimer-1.0.3
stickyhopper-2.3-1.17-1
stitched-snow-1.0.3
terrarian-slimes-1.1-BETA+1.17
tomsstorage-1.1.13-1.17.1
trident_revision-1.0.2
trinkets-3.0.2
true-secret-rooms-1.1.4
TweakMyClient-fabric-mc1.17-1.1.6+build.22
twigs-1.0.1
vanillaplusbiomes-0.3.2
veinmining-fabric-0.0.10-1.17
voicechat-fabric-1.17.1-1.1.0
Walkways-1.0.1
wanderingcollector-1.0.2+mc1.17
whereisit-1.17.1-1.13.2
wirelessnetworks-1.1.2
witherite-0.0.8-hotfix
wraith-silkspawners-1.0.2
wthit-fabric-3.8.0
Xaeros_Minimap_21.14.0_Fabric_1.17.1
XaerosWorldMap_1.15.0.1_Fabric_1.17.1
xlpackets-2.0-1.17
YungsApi-1.17-Fabric-13
</details>

**Logs:**

[crash-2021-07-26_06.10.38-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/6875528/crash-2021-07-26_06.10.38-client.txt)

**Comment by GabrielOlvH** [comment]
Can you try to reproduce it without Paradox Slabs? Someone else has already reported this and removing it fixed it.

**Comment by Footage2-Amply-Pounce** [comment]
So far it seems to be the case, yes. I removed the mod yesterday and no crash happened since then. Is that something that you would be able to work out on your end, or should I report this to the Paradox Slabs dev?

**Comment by GabrielOlvH** [comment]
I don't know what the problem is, reporting it to the Paradox Slabs' dev is probably a good idea.

**Comment by Footage2-Amply-Pounce** [comment]
Got it. And, sadly, I went to check out his page and there's now a notice that says ["This mod is unmaintained. I am willing to transfer its ownership to whoever can and wishes to maintain it."](https://www.curseforge.com/minecraft/mc-mods/paradox-slabs)

Thanks for pointing me in the right direction, though, I will permanently remove Paradox Slabs from my mod list.
