### ISSUE TITLE
[BUG] Can't pull items out of MK Farmer

### ISSUE THREAD

**Issue by Kulturnilpferd** [GabrielOlvH/Industrial-Revolution#272]
**Description:**
Want to pull items from a farmer to a chest. Have tested all item pipes in AOF3, even the classical hopper didn't work...

**Steps to Reproduce:**
Build a Farmer and try to pull items out of it with a hopper or item pipe

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 
 - Industrial Revolution: 
 - Modpack: All of Fabric 3

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
You need to configure the machines item input and output using a Wrench in configure mode

**Comment by Kulturnilpferd** [comment]
Now it's working, awesome thanks for quick reply <3

**Comment by Dargonizer** [comment]
Configuring the machines doesn't do aynthing

**Comment by badbananas1** [comment]
same here nothing happens and its very annoying
