### ISSUE TITLE
[BUG] Crash at startup

### ISSUE THREAD

**Issue by maicol07** [GabrielOlvH/Industrial-Revolution#277]
**Description:**
Industrial Revolution crashes at startup

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.37.1
 - Industrial Revolution: 1.10.0-alpha.12
 - Modpack: Custom

**Logs:**
[crash-2021-07-31_15.18.35-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/6911220/crash-2021-07-31_15.18.35-client.txt)

**Comment by GabrielOlvH** [comment]
This crash is not caused by indrev, some other mod is crashing during init making other mods fail like that
