### ISSUE TITLE
1.16.2/indrev-1.5.1-BETA Modular Workbench progression inaccurate

### ISSUE THREAD

**Issue by Katorone** [GabrielOlvH/Industrial-Revolution#28]
The progression bar in the modular workbench isn't accurate to the percentage of the progression.

![image](https://user-images.githubusercontent.com/918422/90435388-388f7800-e0cf-11ea-8b9b-3db9e8ac6530.png)

**Comment by GabrielOlvH** [comment]
I'll look into it and try to fix for the next update, thanks for the report! Also, weird note, those texts are meant to be very colorful... Don't know why it's all white there.

**Comment by Katorone** [comment]
Could there be another mod interfering?

**Comment by GabrielOlvH** [comment]
I just probably made a mistake somewhere

**Comment by Katorone** [comment]
Let me know if I can help testing.  I'm currently hosting an experimental 1.16.2 dedicated server for this purpose.

**Comment by GabrielOlvH** [comment]
Oh, good to know, this will be helpful to test the next update since it adds a bunch of things (and probably 2x bugs) if the server is still up by then!

**Comment by Katorone** [comment]
It will be!  I'm also open for more players.  We're currently with 5 people, so it's hard to get everything tested.  Though I'm sure the flood of new releases will slow done in a while.  Right now AE2 and its mod interactions are the big thing to test.

**Comment by GabrielOlvH** [comment]
This should be fixed as of 1.6.0-BETA which you can download [https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3043918](here). Thanks for the report!
