### ISSUE TITLE
[REQUEST] Sugarcane recycle into biomass

### ISSUE THREAD

**Issue by Devan-Kerman** [GabrielOlvH/Industrial-Revolution#281]
**Description:**
- Sugarcane should be recyclable into biomass

**Reason:**
- it is plant

**Comment by GabrielOlvH** [comment]
![image](https://user-images.githubusercontent.com/17054373/129399420-64ec80e5-4195-40bd-96a9-29b9773730cf.png)
done

**Comment by Devan-Kerman** [comment]
![image](https://user-images.githubusercontent.com/28693059/129406808-b65a4370-38a4-4ec3-8276-bb9ab436c691.png)
