### ISSUE TITLE
Mining Rig Computer[BUG] 

### ISSUE THREAD

**Issue by zeddyccus** [GabrielOlvH/Industrial-Revolution#282]
**Description:**
- the RIG Computer mining does not stop once it reaches 100% of the mining is this normal or is it a bug?
**Steps to Reproduce:**

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.37.2
 - Industrial Revolution: 1.10.0 alpha 12
 - Modpack: noting

**Comment by Footage2-Amply-Pounce** [comment]
Did you read the Revolutionary guide? It specifically states that the mining rig will keep on going after 100%, but will only collect trash tier blocks, like stone, coal, netherrack etc.

**Comment by zeddyccus** [comment]
yes I read this correctly but it continues to mine iron ore

**Comment by Footage2-Amply-Pounce** [comment]
Ah, should've said so. I'm not sure, but I'd assume iron is considered to be a low tier ore too. Is there anything in the guide about it? I don't recall. If I'm remembering correctly, only the "target" ore gets fully depleted at 100%. For example, in a chunk where your main goal is diamonds, only diamonds would get depleted entirely. If I'm wrong, then it's a bug.

**Comment by GabrielOlvH** [comment]
This is not a bug, it continues to mine ores after it's finished, although it will generate less ores and more of other blocks.

**Comment by zeddyccus** [comment]
Thank you for this feedback and explanation, is it possible to block it as soon as it reaches 100% and also to decrease the quantity that it can generate, with a configuration file?
