### ISSUE TITLE
[BUG] Block#rotate fails during placement with mods like Campanion

### ISSUE THREAD

**Issue by Xechorizo** [GabrielOlvH/Industrial-Revolution#284]
**Description:**
- Placing Item Cable, Lazuli Flux Containers, etc. using mods like Campanion results in the original horizontal orientation kept, instead of the new horizontal orientation. Campanion mod authors advised Block#rotate may be the cause of the failure to reorient the horizontal axis.

**Steps to Reproduce:**
- Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
- Pick up the Tent with the Tent Bag.
- Rotate the Tent.
- Place the Tent.
- Observe the affected horizontally-oriented blocks have wrongly maintained their original orientation.

**Technical Information:**
- Minecraft v1.16.5
- All The Fabric 3 v2.8.5
- Industrial Revolution 1.9.17-BETA
- Fabric v0.11.3
- Fabric API v0.34.7+1.16
- Oracle JDK v16.0.1

**Logs:**
- https://pastebin.com/h5ey6vz1

**Details:**
![image](https://user-images.githubusercontent.com/14857131/128983610-c57798c0-218a-4442-97f9-48614d19a51c.png)
- CPU: Intel Core i7-6900K
- GPU: EVGA RTX 3090 FTW3 ULTRA GAMING
- RAM: G Skill Trident Z RGB 64 GB DDR4
- OS: Windows 10 Pro 21H1

**Comment by GabrielOlvH** [comment]
Those blocks cannot be rotated because their facing properties are stored in the block entity, not the blockstate, and minecraft only provides the blockstate. You also really shouldn't move things like cables this way, that's not very safe. 
I'll be closing this as it cannot be implemented normally.
