### ISSUE TITLE
Can't connect fluid pipes to techreborn industrial grinder or it's tanks

### ISSUE THREAD

**Issue by superdumpling** [GabrielOlvH/Industrial-Revolution#285]
minecraft 1.17.1

Is this behavior intended? if not, can someone point me to a mod that has fluid pipes that works with tech reborn machines

**Comment by GabrielOlvH** [comment]
Please fill the forms correctly when reporting issues. Apparently the compatibility is currently broken but it will be fixed in the future.

**Comment by superdumpling** [comment]
apologies for that, i'm new to github, where do i get the form template?

**Comment by GabrielOlvH** [comment]
This should be fixed in the latest update available on curseforge. Thanks for reporting.
