### ISSUE TITLE
[BUG] Can't use chunk scanner if the server runs more than 170 ticks behind

### ISSUE THREAD

**Issue by Kulturnilpferd** [GabrielOlvH/Industrial-Revolution#298]
**Description:**
As the title claims I can't use the chunk scanner on the server when it runs abot 170 ticks behind.
**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.65.5
 - Fabric API: - 
 - Industrial Revolution: 
 - Modpack: AOF3

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
Just hold it until you get the result, that's common with high ping and low tps
