### ISSUE TITLE
[BUG] EarlyGame incompatibility

### ISSUE THREAD

**Issue by crysthala** [GabrielOlvH/Industrial-Revolution#299]
**Description:** Indrev has an issue with EarlyGame, specifically something to do with recipes. The game launches without a problem, but crashes to desktop when trying to load a world. I always open compatibility issues on both mods' trackers, so this is that. The "proper" report is on the EG tracker. It's got, like, version numbers and logs and stuff. https://github.com/JayCeeCreates/earlygame/issues/32

Thank you! Indrev might still be in development, but it's already good fun :)

**Comment by GabrielOlvH** [comment]
Thanks for the report, however I don't think this is fully fixable. I will fix the crash but EarlyGame's modifications will not have effect on indrev's recipes.

**Comment by crysthala** [comment]
The Sawmill would be kind of a mechanized upgrade for EG's sawing feature anyway, so that should be perfect. Thanks again :)
