### ISSUE TITLE
1.16.2 server crash when connecting mk1 cables

### ISSUE THREAD

**Issue by drakosoldier298** [GabrielOlvH/Industrial-Revolution#30]
https://gist.github.com/drakosoldier298/bcf9dbfd8e83d27cda211e27aebddffb

**Comment by GabrielOlvH** [comment]
This should be fixed as of 1.6.0-BETA which you can download [https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3043918](here). Thanks for the report!
