### ISSUE TITLE
[REQUEST] Sorry if this is misuse of issue report / misplaced - Looking for guide breakdown of all added features as every link provided sends me in circles

### ISSUE THREAD

**Issue by Jmac11927** [GabrielOlvH/Industrial-Revolution#306]
Apologies in advance, I am someone who puts down and picks up MC once every like 2 years, and only for a few weeks or so. I am playing using these mods, and am just trying to get a breakdown on how/what each thing does in this mod, how to power it, transport stuff, etc. The wiki points to the github, the github has the Readme, the Readme points to the main page, and the main page points to the github. So Im all sorts of lost haha.

**Comment by Jmac11927** [comment]
Nevermind - realized you can search all listed items with "@Industrial" and found the book you can craft in-game which breaks it all down. Sorry!

**Comment by Industrial** [comment]
Hi! xD
