### ISSUE TITLE
[VISUAL BUG] Gamer Axe appears to be still in in your hotbar when you drop it

### ISSUE THREAD

**Issue by Squoshy-Boop** [GabrielOlvH/Industrial-Revolution#307]
**Description:**
Gamer Axe (from Industrial Revolution), appears to be still in in your hotbar when you drop it from there when it's active (I suppose because the item is constantly getting updated). If you are in creative, you can even duplicate it (not important), but I somehow managed to completely disappear one.

**Steps to Reproduce:**
- Grab a Gamer Axe
- Drop it several times, one of them will seem to duplicate

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API:  0.40.1
 - Industrial Revolution: 1.10.0-alpha.12
 - Modpack: Another Quality Modpack 2

**Logs:**
- I don't see anything out of the ordinary, but here's the log: https://paste.corebot.dev/ohanasilow.md

**Comment by GabrielOlvH** [comment]
Closing this as I believe it's already fix. If it still happens, please reopen the issue. Thanks for reporting.
