### ISSUE TITLE
[REQUEST] Cables with facades on top of chests

### ISSUE THREAD

**Issue by Gerdathlete** [GabrielOlvH/Industrial-Revolution#310]
**Cables with facades that still allow chests to be opened!**

When you place a facade block into a cable, it makes the block solid, and therefore prevents chests from being opened. This interferes with storage systems where item cables are placed above chests for input/output. Instead, it would be fantastic if these item cables could imitate the block while still allowing chests to be opened if placed underneath them.

**Comment by GabrielOlvH** [comment]
Thanks for suggesting, this is implemented as of 1.11.0-alpha.2 which will be available shortly on CurseForge.
