### ISSUE TITLE
[BUG] A lot of various models fail to load when using Sodium

### ISSUE THREAD

**Issue by Kerfuffles** [GabrielOlvH/Industrial-Revolution#311]
**Description:**
Most of the machines, cable, and pipes fail to load their models, causing the default texture & model to be used when Sodium is installed.

**Steps to Reproduce:**
Install the mentioned mods below with their dependencies, then load the game into a fresh world.

**Technical Information:**
Minecraft 1.17.1
Fabric 0.11.7
Fabric API 0.40.1
IndRev 1.10.0-alpha.12
Sodium 1.1.2-build.9
REI 6.0.279-alpha
Mod Menu 2.0.13

Using their respective dependencies.

**Logs:**
https://pastebin.com/YEYbDsHD

**Details:**
Running on Intel i9 9900KF with RTX 2080 and latest drivers, using the latest Java 16 runtime.

Notable log entries (I'm only going to paste one here)
```[20:30:25] [Render thread/WARN]: Unable to bake model: 'indrev:compressor_mk4#facing=south': java.lang.NullPointerException```
All of the missing models have this error for their respective names/entries.

![image](https://user-images.githubusercontent.com/355687/134833078-73d6fba2-cc4b-4fd8-be88-2af227e708af.png)
![image](https://user-images.githubusercontent.com/355687/134833213-e2fa6c49-91e2-49d7-9251-81bbf9a6fda7.png)
![image](https://user-images.githubusercontent.com/355687/134833248-58bb56b2-ad1a-4884-b394-d2a26e9e7f6f.png)

**Comment by ocram9** [comment]
Try adding Indium, if I remember correclty that fixed it for me

https://github.com/comp500/Indium

**Comment by Kerfuffles** [comment]
> Try adding Indium, if I remember correclty that fixed it for me

I'll give that a try in a few hours, and get back if that fixes it.

**Comment by Kerfuffles** [comment]
That did indeed fix the problem. Thanks!

As a note to @GabrielOlvH, it probably would be good to add that as a note somewhere on CurseForge for those who are using Sodium. I'm relatively new to Fabric (moving over from Forge), so I was not aware of the fix mentioned above, and I'm sure some others may not be either.

**Comment by GabrielOlvH** [comment]
Indium is required with every mod that depends on Fabric's rendering API, it's not an issue exclusive to indrev, but indeed adding information about it would help a lot, thanks.
