### ISSUE TITLE
[BUG] Modular armor tooltip crash with Inspicio

### ISSUE THREAD

**Issue by TheEpicBlock** [GabrielOlvH/Industrial-Revolution#312]
**Description:**
When hovering over any modular armor piece with Inspicio installed, the client will crash. This is due to Inspicio [adding](https://github.com/Queerbric/Inspecio/blob/1.17/src/main/java/io/github/queerbric/inspecio/mixin/ItemStackMixin.java#L107) custom `TooltipData`'s for armor. Inspicio patches the vanilla method to handle this custom `TooltipData`, but Indrev replaces the vanilla method [here](https://github.com/GabrielOlvH/Industrial-Revolution/blob/master/src/main/java/me/steven/indrev/mixin/client/MixinScreen.java)

This can be bypassed by disabling tooltips for armor in the Inspicio config.

**Steps to Reproduce:**
- Install both Indrev & Inspicio
- Grab a modular chestplate
- Hover over it

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.40.1
 - Industrial Revolution: 1.10.0-alpha.12

**Logs:**
https://paste.ee/p/kFXdp

**Comment by GabrielOlvH** [comment]
This has been fixed as of 1.12.0-BETA available on curseforge. Thanks for reporting!
