### ISSUE TITLE
[BUG] [mod interaction]night vision module crash when voxelmap is installed

### ISSUE THREAD

**Issue by DougStoker** [GabrielOlvH/Industrial-Revolution#315]
**Description:**
- turning the modular helmets night vision on when voxelmap is installed causes the game to crash

**Steps to Reproduce:**
- turning the modular helmets night vision on when voxelmap is installed

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.11.6
 - Industrial Revolution: 1.10.0.alpha.12
 - Modpack: one thats been heavily modified by myself so it wouldn't be very useful, mods should be listed in log

**Logs:**
https://pastebin.com/tSiTJp3z

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
This has already been reported before, however I don't think this is caused by indrev and VoxelMap isn't open source so there's nothing I can do about it. You can try reporting it to them.
