### ISSUE TITLE
[BUG] : Machinery texture animations not working when using Iris Shaders in 1.16.5

### ISSUE THREAD

**Issue by Genesis412** [GabrielOlvH/Industrial-Revolution#316]
Description:
- Electric Furnace, Compressor, coal generator and probaly some other machinery's texture animations don't work when using Iris Shaders. Instead, a static texture is shown (looks like the first frame of the animation). For example the Electric Furnace has just the first led led turned on. Indium is also installed.

Steps to Reproduce:
-Install the mentioned mods below, then load the game into a fresh world and put some ore dust into an EF/use a coal generator to generate power/use a compressor.

Technical Information:
 - Minecraft 1.16.5
 - [1.16.5] Fabric API 0.40.1
 - indrev-1.9.18-BETA.jar
 - fabric-language-kotlin-1.6.1+kotlin.1.5.10
 - iris-and-sodium-mc1.16.5-1.1.2+build.4.jar
 - Patchouli-1.16.4-53-FABRIC.jar
 - indium-1.0.0+mc1.16.5

Logs: (probably usless):
https://pastebin.com/w7Pbbq1e

Details:
None relevant.

**Comment by GabrielOlvH** [comment]
I don't think this is caused by indrev as animated textures are a vanilla feature. Please report it on the Iris issue tracker.
