### ISSUE TITLE
[BUG] List of Bugs from AOF4 1.0 Pre-Release

### ISSUE THREAD

**Issue by Frankiscophil** [GabrielOlvH/Industrial-Revolution#317]
**Description:**
- [x] Cannot directly transfer fluid from an IndRev machine to another IndRev machine.

- [x] Round Robin option for Servo on Item Pipes works for only one cycle to multiple chests before focusing on one chest to fill up.

- [x] Modular Armor, Portable Charger, and Gamer Axe cannot be charged by standing or placing said items on the Charging Pad; Armor and Gamer Axe cannot be charged by Portable Charger or Charging Module.

- [x] Item and Fluid Pipes as well as Cables do not properly connect nor disconnect when configured with Wrench; when disconnecting, an adjacent pipe mimics the disconnection and connection, configuring the affected adjacent pipes does not make the pipe that was configured first mimic the new configuration.

- [x] Pump does not output fluid when connected to Fluid Pipe with Output Servo to Tank or machines. It does, however, function with a Retriever Servo.

- [x] Gamer Axe does not activate and instead vanishes in Survival; does not activate in Creative.

- [x] Cables do not simultaneously power more than one machine; a machine must be at full power before Cables can power another machine connected to the line, even so when more than one machine is connected, all machines are no longer being fed energy.

- [x] Unlike other IndRev machines, Heat Generator does not accept input from Kibe Fluid Hopper.

**Steps to Reproduce: These are listed in an order respective to the issues above**
- Two Fluid Infusers placed next to each other. Touching sides configured one Input and one Output. First Fluid Infuser given Water and Sulfur Dust for Sulfuric Acid.

- One line of Item Pipes with multiple chests connected. Output Servo placed on pipe connected to item source and set to Round Robin.

- Connect any power cable from IndRev, Tech Reborn, or Modern Industrialization to Charging Pad from below. Wear Modular Armor with Gamer Axe and have other electrical items in inventory; place Gamer Axe or other armors on Charging Pad; have a fully charged Modular Chestplate with Charging Module and have the rest of the armor uncharged.

- Use Wrench on lines of Item Pipes, Fluid Pipes, and Cables.

- Set up a Pump. Connect Fluid Pipe to Tank with Output Servo.

- Have a fully charged Gamer Axe. Right-click to activate while in Creative. Do the same while in Survival.

- Connect Cables to a power source. Place any machine, I used Compressors, in the line of cables in quick succession; place any machine in the line, wait for it to be fully powered, place another one, then continue if you prefer. Provide all the machines that were powered with ingots to have them run.

- Place Heat Generator. Configure any side as Input then place Fluid Hopper to the corresponding side. Place a tank above then fill it with lava.

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.40.1
 - Industrial Revolution: indrev-1.11.0-alpha.2
 - Modpack: All of Fabric 4

**Details:**
Pipe Connection and Disconnection Issue
https://drive.google.com/file/d/1-uzKludktTqPcvjQgCkiqYddoavIB2oV/view
https://drive.google.com/file/d/1zBOYcxSjC3ZhcaYbHvO51-ki8T6g_Ixc/view
https://drive.google.com/file/d/1vZmZM8JTVIuMkF9e40FIkghd1O6fHKNK/view

Heat Generator/Kibe Fluid Hopper Issue (Ignore the Lava Tower as that has been fixed)
https://youtu.be/HgXzlRwIc1k

**Comment by dandin87** [comment]
Gamer Axe loses energy while disabled/turned off
Only effects Gamer Axe.

**Comment by jbavay** [comment]
tested with indrev-1.11.0-alpha.3.jar
_Unlike other IndRev machines, Heat Generator does not accept input from Kibe Fluid Hopper._
Heat generator seems to not accept fluid neither from indrev pipe.
-Put a Indrev tank. fill it with lava.
- link it with indrev Pipe (tested MK1 & MK3) to heat generator
- Add a ouput servo on the tank (tested also with a retriever)
- configure "Fluid" part to have "input" on linked face
**Result:**: heat generator does not receive any lava.

**Comment by jbavay** [comment]
Version tested: alpha.3
When hitting a mob (tested with villager, golem & drowned & straw dummy) the Gamer Axe disappear after first hit. not anymore in hotbar or inventory.
Tested in creative & survival.

**Comment by Frankiscophil** [comment]
**Description:**

- Modular Armor, Portable Charger, and Gamer Axe cannot be charged by Portable Charger or Charging Module Chestplate.

- Cables still do not simultaneously power more than one machine; a machine must be at full power before Cables can power another machine connected to the line, even so when more than one machine is connected, all machines are no longer being fed energy.

-

**Steps to Reproduce: These are listed in an order respective to the issues above**

- Connect any power cable from IndRev, Tech Reborn, or Modern Industrialization to Charging Pad from below. Wear Modular Armor with Gamer Axe and have other electrical items in inventory; place Gamer Axe or other armors on Charging Pad; have a fully charged Modular Chestplate with Charging Module and have the rest of the armor uncharged.

- Connect Cables to a power source. Place any machine, I used Compressors still as before, in the line of cables in quick succession; place any machine in the line, wait for it to be fully powered, place another one, then continue if you prefer. Provide all the machines that were powered with ingots to have them run.

**Technical Information:**

Minecraft: 1.17.1
Fabric API: 0.40.1
Industrial Revolution: indrev-1.11.0-alpha.4
Modpack: All of Fabric 4

**Comment by MisterZam** [comment]
Bugs!

• Fluid auto-input in indrev machines inserts to both input and output tanks.
• Fluid auto-output in indrev machines outputs both the input and output fluids.
• Wireless Networks cannot accept MI energy
• Progress bar gets stuck when you cancel any processing. Although it resets when you reinsert or insert another. 
• 

Technical Information:

Minecraft: 1.17.1
Fabric API: 0.40.1
Industrial Revolution: indrev-1.11.0-alpha.4
Wireless Networks: wirelessnetworks-1.2-BETA
Modpack: All of Fabric 4

**Comment by GabrielOlvH** [comment]
Closing this as everything was fixed and the update was released. Thanks for the help.
