### ISSUE TITLE
modular workstation power issue

### ISSUE THREAD

**Issue by Monster-Zer0** [GabrielOlvH/Industrial-Revolution#32]
MC:1.16.2
Fabric API 0.19.0+build.398-1.16
indrev 1.6.1

placing module and modular armor in modular workstation causes repeat of drawing of power and never allows progression.

example: https://gyazo.com/04fe355b8bd1d5326283429fb278809f

list of fabric mods: https://hastebin.com/cetapuhazi.sql

**Comment by GabrielOlvH** [comment]
Fixed on 1.6.2-BETA, which you can download [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3047279) once approved. Thanks for the report!
