### ISSUE TITLE
 Corrupt textures

### ISSUE THREAD

**Issue by lolminiyt** [GabrielOlvH/Industrial-Revolution#325]
i have a server with other mods fabric , and some blocks and items are corrupted
![PROBLEMA2](https://user-images.githubusercontent.com/68450478/136674983-cf2a804b-c13e-4577-955c-1a78cc9e83ea.png)

![problema1](https://user-images.githubusercontent.com/68450478/136674985-6baf5d59-2def-4e40-b9b0-4b644ae05732.png)

the most list is: 
![image](https://user-images.githubusercontent.com/68450478/136675000-424a9ed5-e92a-4c80-9457-d014d97ee814.png)
![image](https://user-images.githubusercontent.com/68450478/136675006-c135a451-dbc2-42bb-8a82-d9b202a3d204.png)

**Comment by Footage2-Amply-Pounce** [comment]
Not a bug, install [Indium](https://www.curseforge.com/minecraft/mc-mods/indium).

**Comment by lolminiyt** [comment]
thanks for helping me
