### ISSUE TITLE
[BUG] Indrev 1.11.0-alpha.1 crashes on startup: Mixin apply failed mixins.playerabilitylib.common.json:ServerPlayerEntityMixin

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#327]
**Description:**

The game crashes on start up when indrev 1.11.0-alpha.1 or above is installed. I thought I somehow messed up the build when I built from source myself, however, installing the newly released version from CurseForge also causes the crash.

The issue does not happen with Industrial Revolution 1.10.0-alpha.12.

**Steps to Reproduce:**

1. Install Fabric API
2. Install Fabric language kotlin (fabric-language-kotlin-1.6.5+kotlin.1.5.31)
3. Install IndRev
4. Launch the game

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: fabric-api-0.40.8+1.17
 - Industrial Revolution: indrev-1.11.0-alpha.1
 - Modpack: No other mods were used

**Logs:**

[latest.log](https://github.com/GabrielOlvH/Industrial-Revolution/files/7318201/latest.log)

**Comment by Zethin64** [comment]
Same here - also having this issue. Tried multiple different Fabric API versions but with all of them, no dice. Only thing that works is rolling back to 1.10.0-alpha.12.
