### ISSUE TITLE
[BUG] indev vs TR - Amount may not be negative, but it is: -2560 (AOF4 1.0.0)

### ISSUE THREAD

**Issue by irunatbullets** [GabrielOlvH/Industrial-Revolution#328]
**Description:**
The server crashed and so I grabbed the report. I thought it was the same thing we experienced the other day with dank docks, but that doesn't seem to be the case.

**Steps to Reproduce:**
Unfortunately I don't know what the steps are to reproduce it - luckily/unluckily for the players the server rolled back so I didn't have to remove anything.

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.40.8+ 1.17
 - Industrial Revolution: 1.11.0-alpha.1
 - Modpack: AOF4 1.0.0

**Logs:**
https://paste.alloffabric.com/buyajawaba.yaml

**Comment by GabrielOlvH** [comment]
Thanks for reporting, it should be fixed as of 1.11.0-alpha.2 which will be available shortly on CurseForge.
