### ISSUE TITLE
Crash when outputting from Industrial smelter to a condenser

### ISSUE THREAD

**Issue by Donnydare21** [GabrielOlvH/Industrial-Revolution#33]
[crash-2020-09-01_21.54.36-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/5159104/crash-2020-09-01_21.54.36-server.txt)
[crash-2020-09-01_21.53.52-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/5159105/crash-2020-09-01_21.53.52-server.txt)

**Comment by GabrielOlvH** [comment]
This seems to be an Astromine issue, I've already talked with one of the devs and I believe a fix is on the way. If the issue is actually on Industrial Revolution, reopen the issue and I'll fix it. Thanks for the report!
