### ISSUE TITLE
[1.16.5] Happiness is a Warm Gun compatibility

### ISSUE THREAD

**Issue by WolfBV** [GabrielOlvH/Industrial-Revolution#337]
**Description:**
- When using HWG 1.2.3 and Industrial Revolution 1.9.18 together, new worlds crash when being created. The author of HWG said this is an issue with Patchouli that Industrial Revolution is bundling with its mod.

**Steps to Reproduce:**
- Download Industrial Revolution and Happiness is a Warm Gun. Attempt to create a new world.

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.37.0
 - Industrial Revolution: 1.9.18-BETA
 - Modpack: custom

**Logs:**
- https://pastebin.com/fsGFWFQQ

**Details:**
https://github.com/AzureDoom/HWG/issues/36

**Comment by GabrielOlvH** [comment]
I'll be closing this as 1.9.18 is an old version and isn't supported. If this issue still happens on newer versions, please open a new issue.
