### ISSUE TITLE
[REQUEST] about dubovlenie forge version of the mod

### ISSUE THREAD

**Issue by ForgeLover2** [GabrielOlvH/Industrial-Revolution#341]
**Description:**
I really like your mod, I'm a big fan of the forge. And I would like to see the industrial revolution on the forge version of the game. I'm from Russia, so I use a translator

**Reason:**
Your mod is very good and there is no such high-quality mod on the forge version of the game.

**Comment by GabrielOlvH** [comment]
I'm glad you enjoy the mod but there will not be a Forge version.
