### ISSUE TITLE
[BUG] Fabric API Transfer v1 -> AE2 + Indrev

### ISSUE THREAD

**Issue by red2blue** [GabrielOlvH/Industrial-Revolution#343]
Player crashes when joining after setting up indrev cables into AE2 

https://pastebin.com/NtD3HNzY 

Fabric 1.17.1
Modloader 0.11.7

**Comment by GabrielOlvH** [comment]
This should be fixed as of 1.11.0-alpha.5 which is available on CurseForge. Thanks for reporting!
