### ISSUE TITLE
[BUG] Untagged and unusable copper nuggets

### ISSUE THREAD

**Issue by TheArcaneBrony** [GabrielOlvH/Industrial-Revolution#346]
**Description:**
Copper nuggets aren't tagged as #c:copper_nuggets, making you unable to use them as a copper nugget, even in indrev recipes.
**Steps to Reproduce:**
Use indrev:copper_nugget in any recipe using copper nuggets

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.41.3
 - Industrial Revolution: 1.11.0-alpha.4
 - Modpack: n/a

**Logs:**
- Use a paste service, do not paste the logs directly here.
[Logs](https://paste.ee/p/7NaWs)

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer
![8s1ij7m5QM](https://user-images.githubusercontent.com/13570458/140588094-23fd21b2-d19c-47d2-b324-91a21172708b.gif)

**Comment by GabrielOlvH** [comment]
Not sure what happened, the file definitely [exists](https://github.com/GabrielOlvH/Industrial-Revolution/blob/master/src/main/resources/data/c/tags/items/copper_nuggets.json). Can you send me your latest.log file?

**Comment by TheArcaneBrony** [comment]
Logs uploaded here: [paste.ee](https://paste.ee/p/DBmiN). Not sure what's going on here.

**Comment by GabrielOlvH** [comment]
Closing this as the paste has expired and it's unlikely to be an issue with IndRev. If the issue persists, please open a new report with recent logs.
