### ISSUE TITLE
[BUG] negative number crash

### ISSUE THREAD

**Issue by xxlio109** [GabrielOlvH/Industrial-Revolution#349]
**Description:**
The quantity is negative .
The response is an Indrev issue. 
https://github.com/TechReborn/TechReborn/issues/2598
**Steps to Reproduce:**
unknown 

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: fabric-api-0.42.1+1.17
 - Industrial Revolution: indrev-1.11.0-alpha.4
 - Modpack: AQM2 [v2.9.5a] Hotfix

**Logs:**
https://gist.github.com/xxlio109/d0fdd7c7226cacca4fd6ce402d908054

**Details:**
nope

**Comment by GabrielOlvH** [comment]
This is fixed as of 1.11.0-alpha.5 which is available on CurseForge. Thanks for reporting!
