### ISSUE TITLE
byg support for chopper

### ISSUE THREAD

**Issue by Monster-Zer0** [GabrielOlvH/Industrial-Revolution#35]
indrev 1.6.6 BETA
mc 1.16.2

it seems the chopper doesn't recognize byg tree's

not sure if I can do something with kubejs.. or just need to have the chopper recognize.

**Comment by GabrielOlvH** [comment]
That's strange, if you press F3 and look at a BYG log does it show #minecraft:logs tag on the right side?

**Comment by Monster-Zer0** [comment]
[Yes it does](https://pasteboard.co/Jqkk0SE.png)
