### ISSUE TITLE
[BUG] Crash when placing down a Tank: Sided fluid storage may only be queried for a server world.

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#350]
**Description:**

- Placing down a Tank causes the game to instantly crash.

**Steps to Reproduce:**

1. Install Indrev and its dependencies
2. Launch the game, create a new world, enter an old one or join a server that has the mod installed
3. Grab a Tank and place it anywhere you want

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: 0.42.1
 - Industrial Revolution: indrev-1.11.0-alpha.4
 - Modpack: none

**Logs:**

- https://gist.github.com/Footage2-Amply-Pounce/1c8f75a88d279063a57540a5b7560d32

**Comment by GabrielOlvH** [comment]
This is fixed as of 1.11.0-alpha.5 which is available on CurseForge. Thanks for reporting!
