### ISSUE TITLE
[BUG] Server crash on initialization with alpha 5

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#351]
**Description:**

- When indrev-1.11.0-alpha.5 is installed on a server, it will crash on init.

**Steps to Reproduce:**

1. Install indrev-1.11.0-alpha.5 and start the server

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: 0.42.1
 - Industrial Revolution: indrev-1.11.0-alpha.5
 - Modpack: none

**Logs:**

- https://gist.github.com/Footage2-Amply-Pounce/6f9f4b7060b258b236809fa404f9536e

**Details:**

The crash does not happen on the client.

**Comment by GabrielOlvH** [comment]
This has been fixed as of 1.12.0-BETA available on curseforge. Thanks for reporting!
