### ISSUE TITLE
Incompatibility with Sodium mod

### ISSUE THREAD

**Issue by wwaisath** [GabrielOlvH/Industrial-Revolution#352]
Sodium mod breaks textures for most machines, pipes, and cables.

Tested with only the following mods installed
Industrial Revolution - indrev-1.12.0-BETA.jar (also with 1.11.0 Alpha and 1.12.0 Alpha)
Fabric API - fabric-api-0.42.1+1.17.jar
REI - RoughlyEnoughItems-6.1.329.jar
Sodium - sodium-fabric-mc1.17.1-0.3.2+build.7.jar
Fabric Language Kotlin - fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
Architectury API - architectury-2.6.35.jar
Cloth Config API - cloth-config-5.1.40-fabric.jar

Also tested without Sodium, and there were no broken textures.

![2021-11-11_22 25 08](https://user-images.githubusercontent.com/47764764/141420496-7968b288-25ab-4310-8490-d670c2ed875d.png)

**Comment by BarryBlackCat** [comment]
It's sodium fault, use Indium + sodium to fix that.

**Comment by AlisterGontineac** [comment]
I do, and all that stuffs is just invisible for me. If I place in world.. crash D:

**Comment by GabrielOlvH** [comment]
Those blocks are unfinished and missing a lot of things, you shouldn't use them yet

**Comment by AlisterGontineac** [comment]
ah okay :]
