### ISSUE TITLE
[BUG] Server crash on join: Amount may not be negative, but it is

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#357]
**Description:**

- After restarting my server, I encountered a crash upon joining it. Restarting again let me join just fine, but I figured it's still worth to let you know as it seems very similar to #328. But in their case the exception was thrown at Ticking world, whereas in my case it's Ticking block entity.

**Steps to Reproduce:**

- Just like #328, I dont actually know what exactly happened and so far it only happened once. The only thing I can say is that I was simply restarting the server to upload some updates, and as I joined I spawned next to 10 fully powered Lazuli flux Mk4 containers (the ones mentioned in the crash report).

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: 0.42.1
 - Industrial Revolution: indrev-1.12.0-BETA
 - Modpack: non-public, custom

**Logs:**

- https://gist.github.com/Footage2-Amply-Pounce/0948f67ac499282a249850f46520d759

**Comment by GabrielOlvH** [comment]
This should already be fixed, if it still persists, please open a new report with recent crash logs. Thanks for reporting,
