### ISSUE TITLE
[BUG] Builtin elytra module not allowing flight?

### ISSUE THREAD

**Issue by SpyTheMeme** [GabrielOlvH/Industrial-Revolution#358]
**Description:**
- Give a detailed explanation of the issue
Builtin elytra module doesn't seem to work.

**Steps to Reproduce:**
- Steps to reproduce this behaviour 

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: newest (atm)
 - Industrial Revolution: Newest (atm)
 - Modpack: custom

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
![image](https://user-images.githubusercontent.com/37918654/142054510-1f41dcdc-62e5-48b9-a7ca-b6f1914c4c1b.png)
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
The Builtin Elytra module is unfinished and disabled, I'll be closing this since it isn't really an issue
