### ISSUE TITLE
[BUG] Machine options don't visually update on the first change; all its options reset after a world restart

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [GabrielOlvH/Industrial-Revolution#362]
**Description:**

- When changing settings of a machine (e.g. Rancher), such as "Feed babies", "Mate adults", "Kill after" etc, they will take effect, but will visually reset after you exit and re-open the GUI of the machine.

**Steps to Reproduce:**

1. Place down a Creative Rancher
2. Open its GUI, navigate to the Wrench tab, change any settings you like
3. Close the GUI and open it again; everything got visually reset, but if you have any animals in range you can see that none of the settings were actually reset
4. If you change the settings again, this time it will persist until you change it once more
5. However, once you restart the server/exit the world and re-enter, the machine's settings will reset again

**Technical Information:**

 - Minecraft: 1.17.1
 - Fabric API: 0.43.0
 - Industrial Revolution: indrev-1.12.0-BETA (but this bug has been a thing since very early alpha versions, I just kept forgetting about it...)
 - Modpack: none

**Logs:**

- https://gist.github.com/Footage2-Amply-Pounce/43cca20ba01ac10ebcace6b528301281

**Comment by Mendanbar** [comment]
I'm still seeing these numbers reset in the latest build: 1.13.6-BETA
