### ISSUE TITLE
[BUG] Item Pipe Crash

### ISSUE THREAD

**Issue by DMSledge** [GabrielOlvH/Industrial-Revolution#367]
**Description:**
- Getting a server crash when connecting item pipes to modded storage blocks. May be Dank related issue
**Steps to Reproduce:**
- Connect pipes and servo to a Dank or other modded storage block with larger than 64 stacks and it will crash.

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.42.1
 - Industrial Revolution: 1.12.0-Beta
 - Modpack: custom

**Logs:**
- java.lang.IllegalArgumentException: Amount may not be negative, but it is: -133
https://paste-bin.xyz/23506

**Details:**
Looks kinda like the abnormal stack sizes of danks are overflowing the math in the servos and crashing the server.

**Comment by GabrielOlvH** [comment]
This is an issue with Dank Storage which was already fixed on their end. Updating Dank should fix it. Thanks for reporting
