### ISSUE TITLE
[BUG] Client crashes when trying to create a world when AE2 is also present

### ISSUE THREAD

**Issue by JSJBDEV** [GabrielOlvH/Industrial-Revolution#368]
**Description:**
- Game crashes upon trying to make a world, or open a previously open world

**Steps to Reproduce:**
- Have Applied Energistics 2 an Industrial Revolution in a modpack together
- go to main menu and try to create or open a world

**Technical Information:**
 - Minecraft: 1.18;1
 - Fabric API: 0.44.0
 - Industrial Revolution: 1.13.0-BETA
 - (Applied Energistics 2 - 10.0.0-alpha.8
 - Modpack: Custom

**Logs:**
- [gist.](https://gist.github.com/JSJBDEV/8c78959db13830e4558c7ef1bb204aa3)

**Details:**
It would seem there is some strange interaction happening with the c:wrenches tag that is causing some kind of visual problem that crashes the client, this error only occurs when both mods are present, both mods work fine by themselves

**Comment by DrummerMC** [comment]
I created a PR #369 that fixes this issue
