### ISSUE TITLE
[BUG] Mining rig resource reports do not respect oregen.json

### ISSUE THREAD

**Issue by broman** [GabrielOlvH/Industrial-Revolution#373]
**Description:**
- Even if an ore is disabled in config/indrev/oregen.json, the mining rig will still select veins with this ore in it and generate it. I believe, even though this config affects ore generation in the world, the mining rig should not produce disabled ore.

**Steps to Reproduce:**
1. Disable an ore in config/indrev/oregen.json
2. Use the chunk scanner until you find a vein with the disabled ore
3. Set up the mining rig
4. Observe the disabled ore being extracted 

**Technical Information:**
 - Minecraft: 1.17.1
 - Fabric API: 0.12.11
 - Industrial Revolution: 1.12.0-BETA
 - Modpack: All of Fabric 4, v1.1.3

**Logs:**
- N/A

**Details:**
- N/A

**Comment by broman** [comment]
Also: If anybody has this exact issue and use AoF4 you can simply do a 1:1 conversion from Indrev's tungsten to the one that AoF4 uses. But this issue still persists with those who do not use AoF.

**Comment by NiChrosia** [comment]
One solution would be to add another config (utilizing the pre-existing one is a bad idea since it's for ore block gen rather than veins) (that would automatically generate entries for all vein types) and check whether the vein type is disabled before generating resources in the Mining Rig.

**Comment by broman** [comment]
Since the mining rig mechanics have since changed completely, and since this is taking up my github issues list, I'm closing it.

Thank you for making IndRev, I love this mod!
