### ISSUE TITLE
[BUG]  crashes client on interacion

### ISSUE THREAD

**Issue by wackoamd1** [GabrielOlvH/Industrial-Revolution#377]
**Description:**
- my client crashes whenever i interact with the farmer either after putting it down or when i want to put it down .
- since IR is the last mod i added to the server , from what i have seen in the log ,it has something to do with the energy ui

**Steps to Reproduce:**
- try to put it down and interact or just try to brake if it happens to be able to put down

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 1.12.2
 - Industrial Revolution: 1.13.4 beta
 - Modpack: 

**Logs:**
https://paste.ee/p/u1Zmx

**Details:**
the server just keeps running , its just the client that crashes.
 
edit:
now i only pointed at the farm in my inventory and it took down my minecraft

https://paste.ee/p/IOHmG 

seems to be a incomp with iceberg https://github.com/AHilyard/Iceberg/issues/2

**Comment by GabrielOlvH** [comment]
Thanks for reporting, the first crash is caused by IR and is now fixed, a release will be out soon on CurseForge. Not sure bout the second one though.
