### ISSUE TITLE
[BUG] Hovering over certain items crashes the client

### ISSUE THREAD

**Issue by BrianDuemmer** [GabrielOlvH/Industrial-Revolution#378]
**Description:**
- When mousing over items such as the Pulverizer MK1 or Battery in the player's inventory or crafting table, the client will crash.
- Hovering over the item in REI does not cause a crash.
- The server is not affected.

**Steps to Reproduce:**
- Add 1x Battery to the player's inventory
- Mouse over the battery

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 0.45.2+1.18
 - indrev: Industrial Revolution 1.13.3-BETA
 - indrev-nikolite: Industrial Revolution: Nikolite Expansion 1.0+1.18.1
 - Modpack: Benchmark II 0.5.1

**Logs:**
- Pulverizer Crash: https://pastebin.com/gEiQjU2u
- Battery Crash: https://pastebin.com/RpMcMUDy

**Details:**
The behavior in-game appears the same for both items. The pulverizer crash report resembles issue #377 but the one for Battery looks different. I am thinking that these may be different issues? 

It seems like the problem could also be related to the Nikolite expansion since other items from the mod not related to Nikolite aren't affected. But it's hard to say.

**Comment by GabrielOlvH** [comment]
This is an issue with the "Iceberg" mod which looks like has already been fixed. Updating it should solve this crash.
