### ISSUE TITLE
[BUG] Indrev Rancher MK1-4 chunk issue

### ISSUE THREAD

**Issue by neonbladez2** [GabrielOlvH/Industrial-Revolution#379]
https://github.com/TeamAOF/All-of-Fabric-5/issues/71

**Comment by neonbladez2** [comment]
Has been written in the link above, thought I might as well make an issue here so you would know as well since I'm not sure whether it is a mod issue or a pack issue.

**Comment by GabrielOlvH** [comment]
This has been fixed as of 1.13.5-BETA, please update both server and clients. Thanks for reporting.
