### ISSUE TITLE
[REQUEST] Add configurable input/output to basic machines

### ISSUE THREAD

**Issue by ErrorSys** [GabrielOlvH/Industrial-Revolution#387]
I just started this mod and one thing I think that it is missing, or at least I think should be a feature, is the ability to control what faces of the block correspond to inputs and outputs, or nothing. I find it a bit frustrating when im compressing bronze and it immediately goes into a macerator next to it to do absolutely nothing.

**Comment by GabrielOlvH** [comment]
It does already have it, the guide book explains that you have to use the Screwdriver to change IO configuration
