### ISSUE TITLE
dumb question about fluid infuser

### ISSUE THREAD

**Issue by nlayer** [GabrielOlvH/Industrial-Revolution#389]
I'm unable to find a wiki, and the readme and ingame manual don't provide much details.  For the life of me, I cannot figure out how to get the pump to get water into the fluid infuser.  I can insert into a tank using the servos, but nothing seems to work for the fluid infuser.  am I missing something obvious?

**Comment by Kiolep96** [comment]
... You put a bucket?
Water bucket perhaps?
Also make sure it's fully pwoered.

**Comment by nlayer** [comment]
Perhaps you misread my question.  Your mod is about tech and automation.
It has a fluid pump and fluid pipes.  Can the pump and pipes not be used to
insert water to this machine?

BTW, I really like the design and model for the pump.  The descending pipe
is a nice touch.

**Comment by yorii** [comment]
> I'm unable to find a wiki, and the readme and ingame manual don't provide much details. For the life of me, I cannot figure out how to get the pump to get water into the fluid infuser. I can insert into a tank using the servos, but nothing seems to work for the fluid infuser. am I missing something obvious?

You need to configure the sides of the fluid infuser with a screwdriver, make sure you're on the page for fluids and not items too.
