### ISSUE TITLE
[BUG] Missing textures

### ISSUE THREAD

**Issue by AlbiDR** [GabrielOlvH/Industrial-Revolution#391]
**Description:**
I am playing on a mostly vanilla singleplayer from CurseForge. IR is the (almost) only mod to add blocks. Most of the textures for machines are missing making it extremely hard to figure out things. I have tried to reinstall IR and from a new world but it made no difference. Are these missing texture because any specific reason or any specific incompatibility with any mod in particular? any way to fix it?

**Steps to Reproduce:**
- Just play

**Technical Information:**
 - Minecraft: 1.18
 - Fabric API: 0.12.12
 - Industrial Revolution: 1.13.2 beta
 - Modpack: It's Performance+ (so Vanilla) but I added other mods (63 total). Included are some performance mods like Sodium and its brothers (Starlight instead of Phosporous), Entity culling, FerriteCore, Fast Furnace, Enhanced Block Entities, Discerning Furnaces, Krypton.

**Details:**
I play on an Intel MBair so all these performance mods are basically necessary to play withouth the laptop becoming a furnace itself.
![Screenshot 2022-01-19 at 19 56 39](https://user-images.githubusercontent.com/97815338/150196079-d83a2fdc-e015-4dc7-8ab9-2094b1c4eec1.jpg)
![Screenshot 2022-01-19 at 19 56 18](https://user-images.githubusercontent.com/97815338/150196092-22ccd1c5-6493-41c3-8084-8fd5f2a99445.jpg)

**Comment by AlbiDR** [comment]
A full list of mods and their versions is this.

![Screenshot 2022-01-19 at 20 14 43](https://user-images.githubusercontent.com/97815338/150201238-28420e3d-365e-4ca0-8795-f8b8b1ab56b7.jpg)
![Screenshot 2022-01-19 at 20 14 55](https://user-images.githubusercontent.com/97815338/150201248-a52532c3-9ead-4b6b-953c-5b58354d250e.jpg)
![Screenshot 2022-01-19 at 20 15 06](https://user-images.githubusercontent.com/97815338/150201252-2fd0c8b2-6b57-4734-9d53-1303eea38fe4.jpg)
![Screenshot 2022-01-19 at 20 15 14](https://user-images.githubusercontent.com/97815338/150201255-cbd2fbb5-8d76-4223-8eba-2595a5cc86cb.jpg)
![Screenshot 2022-01-19 at 20 15 25](https://user-images.githubusercontent.com/97815338/150201259-a9544f82-e6e2-4c66-bc4c-db3b7cf3e8c1.jpg)
![Screenshot 2022-01-19 at 20 15 32](https://user-images.githubusercontent.com/97815338/150201263-c1b6ac2a-4539-4966-aa01-a6d6f324f434.jpg)
![Screenshot 2022-01-19 at 20 14 35](https://user-images.githubusercontent.com/97815338/150201265-0c16693e-6476-4cb8-8273-84cc472b78bb.jpg)

**Comment by ZestyBlaze** [comment]
You have Sodium installed I presume. 
You either need to uninstall Sodium OR install Indium with Sodium as well

**Comment by AlbiDR** [comment]
Ok perfect. I checked if there were any dependencies to install but i must have missed Indium. Thanks
