### ISSUE TITLE
[BUG] Game Crash when attempting to craft battery

### ISSUE THREAD

**Issue by ArcSeraphim** [GabrielOlvH/Industrial-Revolution#393]
**Description:**
- Server crash when attempting to craft the battery item

**Steps to Reproduce:**
- Place needed items in the crafting table

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 0.45.0+1.18
 - Industrial Revolution:  1.13.6-BETA
 - Modpack: Valhelsia Enhanced Vanilla - 1.18

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
[crash-2022-01-20_14.52.46-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/7908177/crash-2022-01-20_14.52.46-client.txt)

**Comment by GabrielOlvH** [comment]
This is an issue with the "Iceberg" mod which looks like has already been fixed. Updating it should solve this crash.
