### ISSUE TITLE
[BUG] Cables, Item Pipes, and Fluid Pipes visual bugs.

### ISSUE THREAD

**Issue by Kiolep96** [GabrielOlvH/Industrial-Revolution#394]
**Description:**
Cables, item pipes, and fluid pipes completely glitch upon putting on a shader pack.

**Steps to Reproduce:**
Just load in a shader pack.

**Technical Information:**
 - Minecraft: 1.18 
 - Fabric API: 0.45.0+1.18
 - Industrial Revolution: 1.13.6 BETA
 - Modpack: N/A

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
![image](https://user-images.githubusercontent.com/97376303/150480686-91c98d29-dda6-48fe-a862-3586257f4554.png)

**Comment by Simba98** [comment]
Same issue with IRIS shader loader.
![image](https://user-images.githubusercontent.com/7941967/150669815-16cbf46a-a74e-4eae-8ae0-693a4b36a262.png)

**Comment by GabrielOlvH** [comment]
Unfortunately Optifine is not supported and there is nothing I can do about it.

If you're using Iris shaders I assume you're also using Sodium, which needs Indium to work properly with mods like IR. If it still doesn't work, open a new issue with logs.
