### ISSUE TITLE
Game Crashing with hopper and any cable above

### ISSUE THREAD

**Issue by Anime0258** [GabrielOlvH/Industrial-Revolution#4]
Hi,

the game crashed when an hopper is placed under an cable of any tier!
Crash log: https://pastebin.com/AEuyYGjZ

hope this can be fixed.

**Comment by GabrielOlvH** [comment]
Hey, thank you for reporting! Sorry about the inconvenience, I've already fixed it (0.2.1-BETA) and currently the file is waiting for approval from CurseForge, I will reply here again as soon as it's available, should only take a few more minutes. Thank you for downloading my mod!

**Comment by GabrielOlvH** [comment]
You can now download [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/2994940)!
