### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by JakeYde** [GabrielOlvH/Industrial-Revolution#400]
**Description:**
- A wiki/getting started is needed.

**Reason:**
- Documentation for getting started with the mod is non-existent.

**Comment by GabrielOlvH** [comment]
There is a Guide Book called Revolutionary Guide which will show you some basic things, if you have any other questions feel free to create an issue with the specific question or join the discord to ask them.

**Comment by JakeYde** [comment]
I searched for this item, as previously mentioned however the crafting recipe for it says it needs a MKI circuit, which requires advanced crafting in the mod to make unless it is a random mob drop there's again no clear way to get started either without a wiki or some type of advancement or somesuch in game to get one started.
