### ISSUE TITLE
[BUG] Unsupported method for indrev recipe(s)

### ISSUE THREAD

**Issue by lifes30daytrial** [GabrielOlvH/Industrial-Revolution#401]
**Description:**
- Game starts up fine, but will crash when loading into a single player world.

**Steps to Reproduce:**
- Import/install modpack on Curseforge: [here](https://gofile.io/d/26SbMC)
- Open a singleplayer world
- feel anguish as your minecraft disintegrates

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: fabric-api-0.42.0+1.16.jar
 - Fabric Modloader: 0.12.11
 - Industrial Revolution: indrev-1.9.18-BETA.jar
 - Modpack: (Unofficial) death by sandwich

**Logs:**
- [pastebin.com](https://pastebin.com/X8wRht0G)

**Details:**
not 100% certain indrev causes the crash but the crashlog said something about indrev so here i am

**Comment by GabrielOlvH** [comment]
Thanks for reporting, sadly IR is not receiving updates for 1.16.5 anymore. This was an old conflict between NBTCrafting mod and IR which has already been fixed in later versions.
