### ISSUE TITLE
[BUG] starting a server with indrev causes error

### ISSUE THREAD

**Issue by n-ngai** [GabrielOlvH/Industrial-Revolution#402]
I started fabric server with indrev, whenever i try to join, it gives this error message

io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer indrev:recycle

**Comment by GabrielOlvH** [comment]
Please make sure both client and the server have the same versions, if the issue persists, open a new issue with client and server logs.
