### ISSUE TITLE
[BUG] Placing Rancher crashed the client

### ISSUE THREAD

**Issue by WhyTheF8CKis-ICMan-NotAvailable** [GabrielOlvH/Industrial-Revolution#403]
**Description:**
Placed an Industrial Revolutions Rancher into the world, and the client crashed.  The server kept running as if there was no problem.

**Steps to Reproduce:**
Place rancher MK1 in the world.

**Technical Information:**
 - Minecraft:   1.18.1
 - Fabric API:   Don't know.  Mod was not in the list.  Not present?
 - Industrial Revolution:   v1.13.4-BETA
 - Modpack:   All of Fabric 5

**Logs:**
https://pastebin.com/uNXPza4h

**Details:**
No screenshot to show.  I edited the world using Amulet, and deleted the rancher.  That allowed me back in, but the rancher was still in my character's hand.  I tried to place the rancher and the same thing happened again.  Client crashed,  Server still running.  Went back in with Amulet, and the block was not there.  But, I guess the server didn't save the placement, because I was able to get back in immediately, and the rancher was still in my character's hand.

**Comment by GabrielOlvH** [comment]
Thanks for reporting, but this has already been fixed in later versions. Update the mod.
