### ISSUE TITLE
[REQUEST] Add fluid input to heat generator

### ISSUE THREAD

**Issue by WhyTheF8CKis-ICMan-NotAvailable** [GabrielOlvH/Industrial-Revolution#404]
**Description:**
- Can't pipe lava into the heat generator.  This seems like an oversight, or a weird choice.  I like to automate everything, so would like to see this added, please.
**Reason:**
- Because all machines should be able to input stuff.  Why have machines at all if not in service to automation?

**Comment by GabrielOlvH** [comment]
The Heat Generator does support fluid input, make sure you are configuring it correctly using a Screwdriver and if you're using pipes, make sure you're using the correct servos.
