### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by CataratasDolly** [GabrielOlvH/Industrial-Revolution#410]
Whenever I hover my mouse on an item from Indrev my game crashes.
I can hover Indrev items from REI just fine, but not from my inventory or from the AE2 terminal.

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 0.46.4+1.18
 - Industrial Revolution: 1.13.6-BETA

**Logs:**
[crash-2022-02-12_21.23.09-client.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/8054785/crash-2022-02-12_21.23.09-client.txt)

**Comment by GabrielOlvH** [comment]
This is an issue with the "Iceberg" mod which I believe is already fixed, updating it should stop the crash.
