### ISSUE TITLE
Incompatibility with sodium

### ISSUE THREAD

**Issue by BMAB2012** [GabrielOlvH/Industrial-Revolution#414]
Description:
When paired up with sodium some of the items such as the pipes and the machines (generators, solar panels, etc.) do not load their textures correctly. An example image of the items and blocks is attached.

Steps to Reproduce:
Install both mods at the same time.

Technical Information:
Minecraft: 1.18.1
Fabric API: latest
Industrial Revolution: latest
Modpack: sodium (latest) and IR

Logs:
No errors

![image](https://user-images.githubusercontent.com/67931416/154567509-fdd68c1b-de79-43e6-bf88-abcd7087f68e.png)

**Comment by ZestyBlaze** [comment]
Install Indium and they'll load properly

**Comment by BMAB2012** [comment]
That worked! I was not aware of Indium. Thanks!
