### ISSUE TITLE
[BUG] 1.18.1 Server Crash due to Ticking Block Error

### ISSUE THREAD

**Issue by TheDragonGamer** [GabrielOlvH/Industrial-Revolution#419]
**Description:**
- Crashing on the server due to a coal generator block that produces a Ticking block entity exception

**Steps to Reproduce:**
- crashes on startup

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 0.46.1+1.18
 - Industrial Revolution: 1.13.6 beta
 - Modpack:  Bolas Dos

**Logs:**
- https://pastebin.com/pQ3njc2B
**Details:**
coincidently enough Bolas Dos was designed to crash to desktop if you try and create a world, so the only playable instance of sed mod pack that will ever run will be this server

**Comment by aria1th** [comment]
Can you provide setup that made crash briefly?

**Comment by TheDragonGamer** [comment]
It was a coal generator connected to an mk4 cable, next to a heat generator that was empty

**Comment by TheDragonGamer** [comment]
update: fixed it by continuing to restart. I noticed the ticking time was decreasing after each restart, now it isn't crashing
