### ISSUE TITLE
[BUG]  End biome vein types are not loaded due to missing '_' & "END" is not correct

### ISSUE THREAD

**Issue by aria1th** [GabrielOlvH/Industrial-Revolution#420]
**Description:**
- All of endstone should be end_stone
- "END" should be replaced with "THEEND"

**Steps to Reproduce:**
check json files.
I'll make quick PR for this.
**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: *
 - Industrial Revolution: 1.13.6
 - Modpack: Any

**Comment by GabrielOlvH** [comment]
Veins don't exist anymore so this is technically fixed :P
Thanks for reporting anyway
