### ISSUE TITLE
[BUG] Possible compatibility issue, where items turn invisible (Not caused by sodium)

### ISSUE THREAD

**Issue by snotknobbel** [GabrielOlvH/Industrial-Revolution#428]
**Description:**
- When using both indrev and a host of mods, some of the items has no visible textures
<img width="334" alt="parsecd_lCKVkGGv0f" src="https://user-images.githubusercontent.com/44928212/158207301-f31a6440-fbf6-46c9-b3cc-2b3ff6e03102.png">
When placing the steam engine block or biological composter and breaking them the game crashes, these also has no textures, being invisible and glitching out the textures beneath creating a x-ray effect

**Steps to Reproduce:**
- Install indrev
- Install other mods
- profit

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: fabric-0.13.3
 - Industrial Revolution: indrev-1.13.6-BETA.jar
 - Modpack: custom (modlist;https://p.sc2.nl/hTPqW) 

**Logs:**
- Use a paste service, do not paste the logs directly here.
- https://p.sc2.nl/7Soip

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by GabrielOlvH** [comment]
Those blocks are unfinished and shouldn't be used yet
