### ISSUE TITLE
Auto insert heatsinks/fans/cooler cells in machines

### ISSUE THREAD

**Issue by mnsnownutt** [GabrielOlvH/Industrial-Revolution#432]
Pretty much the title.  Right now, it is hard to automate and optimize machines and factories, as you spend time running around checking the status of the heatsinks and have to resupply.  This will mess up some set ups, from an efficiency standpoint, when you get it optimized and then come back a half hour later after doing something else, only to find your system backing up due to the heatsink getting used up in one of the machines and then slowing down.  

It would be much less tedious and more of an automation set up to allow the auto-insertion of heatsinks through item pipes and you could then pipe them to numerous machines from a single chest.

One additional thing would be to make heatsinks stackable as well in chests, even if only one can go in the machine.

**Comment by GabrielOlvH** [comment]
Thanks for suggesting, this will be possible in the next update which will be available on CurseForge soon.
