### ISSUE TITLE
[BUG] April fool mixin crashes game

### ISSUE THREAD

**Issue by Apache553** [GabrielOlvH/Industrial-Revolution#434]
**Description:**
There's something wrong with the mixin plugin: "`me.steven.indrev.mixin.aprilfools.AprilFoolsMixinConfigPlugin`". Today is April 1, the game crashes at very beginning every time. And the game launches well before the day. I have tried deleting the line `"plugin":"me.steven.indrev.mixin.aprilfools.AprilFoolsMixinConfigPlugin",` in `indrev.mixins.json`, then the game launches as normal.

**Steps to Reproduce:**
- Set system date to April 1st.
- Launch game with indrev installed.
- The game failed to start.

**Technical Information:**
 - Minecraft: 1.18.1
 - Fabric API: 0.45.0+1.18
 - Industrial Revolution: 1.13.7-BETA
 - Modpack: -

**Logs:**
https://pastebin.mozilla.org/bZ4vF3y4

**Comment by 8w-gremlin** [comment]
I get this. can't play the game

**Comment by GabrielOlvH** [comment]
Updating to https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3725959 should fix this, sorry about this issue

**Comment by MSandro** [comment]
same in 1.17.1!
I hope you can bring a fix for this soon. Please.
