### ISSUE TITLE
[BUG] 1.18.2 indrev_waterAffinityUpwards could not find any targets / mod not version locked to 1.18.1

### ISSUE THREAD

**Issue by milkev** [GabrielOlvH/Industrial-Revolution#435]
**Description:**
When attempting to use this mod, the game crashes early during loading. seems to be something about "indrev_waterAffinityUpwards could not find any targets"
maybe has something to do with 1.18.1 vs 1.18.2, but the mods not version locked.

**Steps to Reproduce:**
1. install latest (as of this report) version of fabric loader and api, indrev and fabric language kotlin
2. attempt to boot up game

**Technical Information:**
 - Minecraft: 1.18.2
 - Fabric API: 0.48.0
 - Industrial Revolution: 1.13.8-BETA
 - Fabric Language Kotlin: 1.7.2+kotlin.1.6.20

**Logs:**
https://pastebin.com/f18Gp1Kd

**Details:**

**Comment by OverloadedWithMods** [comment]
how the hell did u get ur hands on the 1.18.2 version

**Comment by milkev** [comment]
this isnt version locked to 1.18.1, that is part of the issue that im bringing up here.
https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3725959

**Comment by HijackHornet** [comment]
1.18.2 version is expected soon.
On cursed its not flagged 1.18.2 so idk what you expect..

**Comment by milkev** [comment]
lots of mods are only flagged 1.18.1 but still work on 1.18.2. Im here posting that it doesnt work on 1.18.2 despite being marked internally (in the fabric.mod.json) that it can, and the error log in hopes that it will help the devs update. idk why yall are getting so angry about this lol.

**Comment by HijackHornet** [comment]
I am absolutly not angry sorry if you understand it otherwise.
I though it was not marked compatible 1.18.2 in the json file hence my response

**Comment by milkev** [comment]
the current latest release on curseforge (and the one i linked here) is labeled as compatable with all versions equal to or greater than 1.18, which includes 1.18.2

**Comment by OverloadedWithMods** [comment]
well mods that are labelled as that don't follow it to 1.18.2 as it has ALOT of breaking changes

**Comment by milkev** [comment]
how ab yall just drop it and let the devs deal with it?

**Comment by OverloadedWithMods** [comment]
this thread has no point of being here because this 'bug' isn't actually a bug.

**Comment by liquidev** [comment]
If anyone wants to run the mod on 1.18.2, the `master` branch already contains code compatible with the version. There is some tweaking that needs to be done before the mod compiles though, namely removing publishing from the gradle build file:
```patch
diff --git a/build.gradle b/build.gradle
index 2e5b306..e99ce26 100644
--- a/build.gradle
+++ b/build.gradle
@@ -178,33 +178,33 @@ jar {
     exclude("me/steven/indrev/datagen")
 }
 
-// configure the maven publication
-publishing {
-    publications {
-        mavenJava(MavenPublication) {
-            // add all the jars that should be included when publishing to maven
-            artifact(remapJar) {
-                builtBy remapJar
-            }
-            artifact(sourcesJar) {
-                builtBy remapSourcesJar
-            }
-        }
-    }
-
-    // select the repositories you want to publish to
-    repositories {
-        maven {
-            url "https://maven.cafeteria.dev/releases"
-            credentials {
-                username = project.property("mcdUsername")
-                password = project.property("mcdPassword")
-            }
-            authentication {
-                basic(BasicAuthentication)
-            }
-        }
-    }
-}
+// // configure the maven publication
+// publishing {
+//     publications {
+//         mavenJava(MavenPublication) {
+//             // add all the jars that should be included when publishing to maven
+//             artifact(remapJar) {
+//                 builtBy remapJar
+//             }
+//             artifact(sourcesJar) {
+//                 builtBy remapSourcesJar
+//             }
+//         }
+//     }
+// 
+//     // select the repositories you want to publish to
+//     repositories {
+//         maven {
+//             url "https://maven.cafeteria.dev/releases"
+//             credentials {
+//                 username = project.property("mcdUsername")
+//                 password = project.property("mcdPassword")
+//             }
+//             authentication {
+//                 basic(BasicAuthentication)
+//             }
+//         }
+//     }
+// }
 
 compileKotlin.kotlinOptions.jvmTarget = "16"

```
Afterwards it's as simple as running `./gradlew build`.

**Comment by GabrielOlvH** [comment]
As already stated, the mod isn't updated to 1.18.2 yet. The update will be released shortly.
