### ISSUE TITLE
[BUG] Game does not boot if keybindings are unbound.

### ISSUE THREAD

**Issue by xMGZx** [GabrielOlvH/Industrial-Revolution#448]
**Description:**
Game does not boot if keybindings are unbound.

**Steps to Reproduce:**
1. Launch the game with indrev installed
2. Unbind "Modular item configuration" and "Toggle Gamer Axe" by clicking on the keybinding and pressing the "Escape" key.
3. Reboot the game, and notice the game will not boot.

**Technical Information:**
 - Minecraft: 1.18.2
 - Fabric API: 0.51.1
 - Industrial Revolution: 1.14.0-BETA
 - Modpack: Another Quality Modpack 2 v1.1.1

**Logs:**
https://paste.corebot.dev/denilimuxi.md

**Comment by GabrielOlvH** [comment]
This looks like a mixin from Just Enough Keys causing the crash, not an issue with Indrev.

**Comment by rhjdvsgsgks** [comment]
> This looks like a mixin from Just Enough Keys causing the crash, not an issue with Indrev.

still reproducible even if only Indrev (and fabric api & fabric lang kotlin) installed

ps: you may take a look at https://github.com/AmyMialeeMods/half-doors/issues/2 and their fix (maybe this https://github.com/AmyMialeeMods/half-doors/commit/44556aa29d61f4a1ad0341e275aa6bf8182f81c5#diff-3cf6db77f35033985eb6fb8ec30799b4a251d95bbe37028d8925ed07e29757d7R178)
