### ISSUE TITLE
[Performance Issues 1.18.2] Spark says Drill is Causing MSPT Hikes

### ISSUE THREAD

**Issue by itsdinkd** [GabrielOlvH/Industrial-Revolution#450]
**Description:**
In a dedicated server, its been lagging. Looking at the profiler, its pointing to drill among other things

https://spark.lucko.me/DubQlYKl1M?hl=5482

**Steps to Reproduce:**
run a server
have multiple people in
drill
lag?
**Technical Information:**
 - Minecraft: 1.18.2
 - Fabric API: 0.51.1
 - Industrial Revolution:  1.1.4-0 Beta
 - Modpack: Another Quality Modpack 2

**Logs:**
https://spark.lucko.me/DubQlYKl1M?hl=5482

**Comment by GabrielOlvH** [comment]
Mining with a lot of range upgrades is performance heavy and specially bad for servers with lots of players but not a lot can be done about that. It also looks like Dimensional Doors might actually be using resources most. 
I'll be closing this as there's not anything that can be done, but thanks for reporting anyway!
