### ISSUE TITLE
[BUG] No tool to get Tank in survival once placed

### ISSUE THREAD

**Issue by esotericdesign** [GabrielOlvH/Industrial-Revolution#451]
**Description:**
Wrench and Screwdriver have no effect on Tanks, while Pickaxe and other tools just destroy them, leaving no drop.
Also, there is no Tank entry in the Revolutionary Guide to look up, except from it being a crafting component for Fluid Infuser.

**Steps to Reproduce:**
- Place a Tank and try using anything to mine it

**Technical Information**
- Mod version: 1.14.0-BETA for Fabric 1.18.2

**Comment by smoofine** [comment]
still cant break the tank in this version
