### ISSUE TITLE
[BUG] Biomass generator wastes fuel

### ISSUE THREAD

**Issue by qu1ck** [GabrielOlvH/Industrial-Revolution#484]
**Description:**
- Biomass generator wastes fuel endlessly, even if it's at full charge and nothing is connected to it

**Steps to Reproduce:**
- Put fuel into biomass generator, watch it burn away contributing to the climate change of the minecraft world

**Technical Information:**
 - Minecraft: 1.18.2
 - Fabric API: 0.57.0
 - Industrial Revolution: 1.14.0-BETA 
 - Modpack: AllOfFabric 5 v1.3.1

**Comment by Vandurmed** [comment]
Also applies to the CoalGenerator.

Seems that energy generates up to a multiple of 16 and gets stuck at 992 for the coal generator.
As this is not the max (1000) it keeps burning items.

Version : 1.19.2

**Comment by misqcl** [comment]
No way this isn't patched yet ....

**Comment by esotericdesign** [comment]
> Seems that energy generates up to a multiple of 16 and gets stuck at 992 for the coal generator. As this is not the max (1000) it keeps burning items.

Sadly, it's even worse. I tampered with config files a bit, and fuel is wasted even if capacity is set to 10 times its ratio. Set it to 992, the energy will be stuck at 976. Set it to 800, it'll be stuck at 784.

**Comment by douglasg14b** [comment]
> No way this isn't patched yet ....

On latest on 1.20.1 nope.

Can't really stuff things into generators because they burn it forever...

**Comment by GabrielOlvH** [comment]
Fixed as of 1.16.2, thanks for reporting.
