### ISSUE TITLE
[BUG] Lazuli flux capacitors don't fill again

### ISSUE THREAD

**Issue by Cryptiiiic** [GabrielOlvH/Industrial-Revolution#509]
**Description:**
Power won't refill again after switching output back to input.

**Steps to Reproduce:**
After switching  from input to output it will start to drain(if your machines are using power). Once it hits zero and you per say, want to refill power, it won't. When you switch from output back to input, its stuck at zero. The only fix is to break the cable connected on that specific side and place it back down.

I guess there is a block update mechanic with the mk cables that seems to be bugged for i/o.

**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: 0.14.11
 - Industrial Revolution: 15.1-beta
 - Modpack: Dreamcraft for 1.19

**Logs:**
Didn't see anything

**Details:**
None

**Comment by douglasg14b** [comment]
Same issue here as well on latest

**Comment by GabrielOlvH** [comment]
Fixed as of 1.16.2, thanks for reporting.
