### ISSUE TITLE
No recipe for Nikolite ingots[BUG] 

### ISSUE THREAD

**Issue by MichiruAvali** [GabrielOlvH/Industrial-Revolution#522]
**Description:**
- I am unable to find a way to craft the normal nikolite ingot and the enriched nikolite ingot: Its not listed in the guide or JEI

**Steps to Reproduce:**
- try to find a recipe for the nikolite and enriched nikolite ingot in the guide or JEI, there is no one

**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: 0.14.13
 - Industrial Revolution: indrev 1.15.2 beta
 - Modpack: WhitepointSMP 0.8.5

**Logs:**
- not needed

**Details:**
- I have tried things from other mods or modpacks but nothing worked, either its really not in the mod yet or I am blind lol

**Comment by MichiruAvali** [comment]
[SOLUTION]
Put Iron ingots and nikolite Dust into the solid infuser

**Comment by AstridHornBrorholt** [comment]
how about enriched nikolite ingots then?

edit: I found all recipes json-encoded in this folder: https://github.com/GabrielOlvH/Industrial-Revolution/tree/master/src/main/resources/data/indrev/recipes

Enriched nikolite dust is obtained from diamond dust and nikolite dust in the infuser. This enriched nikoklite dust is then infused with a nikolite ingot.
