### ISSUE TITLE
[BUG] The patchouli book doesn't work at all 

### ISSUE THREAD

**Issue by CassieRoseZA** [GabrielOlvH/Industrial-Revolution#538]
**Description:**
- Give a detailed explanation of the issue
The patchouli book doesn't work at all after crafting
**Steps to Reproduce:**
- Steps to reproduce this behaviour
1. Craft Revolutionary Guide
2. Open Guide
3. Nothing happens
**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: 0.85.0+1.20.1
 - Industrial Revolution: 1.16.0-BETA
 - Modpack: n/a

**Logs:**
- Use a paste service, do not paste the logs directly here.
https://mclo.gs/8oJpucx
**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

**Comment by RemagOfficial** [comment]
that's not an issue with the mod probably, that would be patchoulis fault

**Comment by spoorn** [comment]
Other patchoulli books are working for me, only industrial revolution's doesn't work

**Comment by GabrielOlvH** [comment]
Looks like patchouli had a breaking change in a recent update, I'll update soon.

**Comment by GabrielOlvH** [comment]
This is already fixed, thanks for reporting.
