### ISSUE TITLE
[BUG] Recipes for bronze, steel, electrum, and lead plates don't work

### ISSUE THREAD

**Issue by douglasg14b** [GabrielOlvH/Industrial-Revolution#541]
**Description:**
Unsure why, but the recipes don't show when clicked on in JEI, and it doesn't work in a crafting grid. Iron, copper, and tin plates work just fine

It's odd that they don't show up in JEI search, and there is no recipe for them either.

Ones that don't work and don't appear to have recipes (may be more?)

- bronze
- steel
- electrum
- lead
- silver

**Steps to Reproduce:**
Unsure

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: Latest (As of today)
 - Industrial Revolution: Latest (As of today)
 - Modpack: DarkRPG (Plus AE2, Almost Unified, and Powah!)

![image](https://github.com/GabrielOlvH/Industrial-Revolution/assets/1400380/54c2daa7-9f2d-43a0-a1a5-91e3df82a8dd)

**Comment by douglasg14b** [comment]
Nikolite ingots also don't appear to have a recipe.

Removed Almost Unified, doesn't appear to fix the problem. 

Edit: The guide book also doesn't work, it's craftable, but doesn't open.

> [23:25:40] [Render thread/ERROR]: Failed to load book indrev:indrev defined by mod indrev, skipping
java.lang.IllegalArgumentException: Book indrev:indrev has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.

Might be why

**Comment by Toarulle** [comment]
Found the same issue. Have only tried Bronze plates so far since I don't have the other items.
Using the same pack (DarkRPG) with only Industrial Revolution and AE2 added.

**Comment by douglasg14b** [comment]
Yikes, any workarounds? I can't even use JEI to spawn the items in and put them in a trading post or something since none of the plates show up in the search 😬

**Comment by douglasg14b** [comment]
@Toarulle Looks like it's because JEI isn't supported. You'll need to turn off JEI & EMI and replace them with REI.

Note that in the curse modpack manager this may also turn off a bunch of other mods, watch out for that.

**Comment by GabrielOlvH** [comment]
Yes, IR only has compatibility with REI, not JEI. The patchouli book issue will be fixed today. Some plates can only be crafted on a compressor.

**Comment by GabrielOlvH** [comment]
This is fixed as of 1.16.1, thanks for reporting! You can download it on Modrinth while it's not available on CurseForge.
