### ISSUE TITLE
[query] Modrinth

### ISSUE THREAD

**Issue by Jamalam360** [GabrielOlvH/Industrial-Revolution#542]
I couldn't find a Discord or anything, so I'm having to ask here. Is there a reason that Modrinth does not have all the same versions as Curseforge (namely the 1.20.1 betas)?

thanks :)

**Comment by GabrielOlvH** [comment]
That was a mistake on my part, those versions are actually 1.20, I marked them as 1.19.X by accident apparently. This was already fixed.

**Comment by Jamalam360** [comment]
Thanks!
