### ISSUE TITLE
[BUG] Coal Generator continues to burn coal even when full. Making it quite difficut to use.

### ISSUE THREAD

**Issue by douglasg14b** [GabrielOlvH/Industrial-Revolution#544]
**Description:**

The coal generator keeps on burning coal even when full. This means it always burns coal at the maximum speed, regardless of energy actually used. 

This makes the bloc quite tedious and frustrating to use, as it takes the automation part of machines away since it requires babysitting to not chew through all your coal.

**Steps to Reproduce:**
1. Use the coal generator
2. Let it fill up
3. Watch it keep burning all the coal that goes into it

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API:  0.81.6
 - Industrial Revolution: 1.16-BETA
 - Modpack: N/A

**Logs:**

No relevant logs, assumed this is a clogic bug

**Details:**

![image](https://github.com/GabrielOlvH/Industrial-Revolution/assets/1400380/e4c9e7dd-9f2d-4f83-8346-f63fe9773f23)\

The generator doesn't fill up all the way, and the code here means it just keeps on generating: 
https://github.com/GabrielOlvH/Industrial-Revolution/blob/012a1b83f39ab50a10d03ef3c1a8e2651e517053/src/main/kotlin/me/steven/indrev/blockentities/generators/SolidFuelGeneratorBlockEntity.kt#L22-L38

**Comment by GabrielOlvH** [comment]
Fixed as of 1.16.2, thanks for reporting.

**Comment by douglasg14b** [comment]
Thanks @GabrielOlvH!
