### ISSUE TITLE
[BUG] Item Pipe Filter does not show what items are in filter

### ISSUE THREAD

**Issue by douglasg14b** [GabrielOlvH/Industrial-Revolution#545]
**Description:**

The items in the item pipe filter at least for the output servo show no icons. Hovering over them will show what the contents are.

**Steps to Reproduce:**

Use an output servo and add items to the filter

**Technical Information:**

-   Minecraft: 1.20.1
-   Fabric API: 0.81.6
-   Industrial Revolution: 1.16-BETA
-   Modpack: N/A

**Logs:**

no relevant logs generated

**Details:**

![image](https://github.com/GabrielOlvH/Industrial-Revolution/assets/1400380/0461633d-2af9-4b17-af62-58f15c8c038c)

**Comment by GabrielOlvH** [comment]
Thanks for reporting! Will be fixed in the next update.
