### ISSUE TITLE
Chunk scanner Disappear [BUG] 

### ISSUE THREAD

**Issue by ZAIAC001** [GabrielOlvH/Industrial-Revolution#548]
Install this mod
Start building mining farm
I need to scan chunk for ores
BUT there is no such item at all

No in jei, no by give command

(mc 1.20.1 Fabric

**Comment by GabrielOlvH** [comment]
The Chunk Scanner has been removed, you need to use data cards on the miner now.

**Comment by ZAIAC001** [comment]
So how does it works?
I build miner, place drill and place bit in it.
Power it up
Even write that card
But miner still not work
