### ISSUE TITLE
[BUG] Fisher consumes Spectrum mod's Bedrock fishing rod in one cycle

### ISSUE THREAD

**Issue by Aphyxia** [GabrielOlvH/Industrial-Revolution#549]
**Description:**
- The (Advanced) Fisher machine consumes Spectrum mod's supposedly unbreakable Bedrock fishing rod in one cycle.
- The same does not happen when I insert a fishing rod made unbreakable by the Things mod's hardening catalyst.
- Addition: The Things unbreakable does visually not seem to take any damage but the fishing rod still breaks after about 64 durability ticks like usual. This is in stark contrast to something like the Chopper, where one unbreakable axe will last forever.

**Steps to Reproduce:**
- Insert the rod into the machine.

**Technical Information:**
 - Minecraft: 1.19.2
 - Fabric API: 0.76.0
 - Industrial Revolution: 1.15.1-BETA
 - Modpack: Prominence I 2.0.1

**Logs:**
- Nothing in logs.

**Comment by GabrielOlvH** [comment]
Thanks for reporting! Will be fixed in the next update.

**Comment by Aphyxia** [comment]
Thanks! You work fast.
You had already fixed the original problem when I typed an additional version of the problem where items made unbreakable with the Things mod does visually not seem to take any damage but the fishing rod still breaks after about 64 durability ticks like usual.
I don't suppose this commit fixes that too?
