### ISSUE TITLE
[BUG] SlaughterBlockEntity and RancherBlockEntity crash the game 

### ISSUE THREAD

**Issue by JINZhao2000** [GabrielOlvH/Industrial-Revolution#552]
**Description:**
- The Slaughter and Rancher will crash the game

**Steps to Reproduce:**
- Place the slaughter or rancher
- Give electricity for them

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: 0.85.0+1.20.1
 - Industrial Revolution: 1.16.4-BETA
 - Modpack: https://drive.google.com/file/d/1hrk2uf9zocmGzCJneJ7mNiaItPhhrtSV/view?usp=sharing

**Logs:**

[crash-2023-08-22_20.31.24-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/12412057/crash-2023-08-22_20.31.24-server.txt)
[crash-2023-08-22_20.53.33-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/12412058/crash-2023-08-22_20.53.33-server.txt)

**Comment by Lyk89** [comment]
Has anyone found a solution please?

**Comment by 8itoDevM** [comment]
Is this happening in the forge and fabric versions, or just the fabric version?

**Comment by Lyk89** [comment]
in my case only with the fabric version

**Comment by JINZhao2000** [comment]
It crashes the fabric version; see https://github.com/CafeteriaGuild/fake-player-api/

**Comment by JINZhao2000** [comment]
fixed in 1.16.5-BETA version of mod
