### ISSUE TITLE
Add powah's ores mod to data for mining rig (or a solution to add it)

### ISSUE THREAD

**Issue by Neauzis** [GabrielOlvH/Industrial-Revolution#562]
**Description:**
Hello, there is a solution to add mods ores to data card encoder, or can i manually add it ? ty

**Reason:**
To have more compatibility with others mods

**Comment by solonovamax** [comment]
You can add it in the `config/indrev/mining_rig_config.json` file.

**Comment by Neauzis** [comment]
ty
