### ISSUE TITLE
[BUG] Missing crafting recipe for many items, both in JEI and in Revolutionary Guide.

### ISSUE THREAD

**Issue by DevKemal** [GabrielOlvH/Industrial-Revolution#574]
**Description:**
Some items like bronze and nikolite don't show up on JEI menu and don't have any explanation on how to craft them in the Engineer's Manual. For example I want to craft second tier solar generator, and recipe shows I need two enriched nikolite ingots and two electrum plates. JEI has no recipe for those, Engineer's manual doesn't mention how to craft any of those, it only has the recipe for the machine, and it seems it expects me to figure out what electrum is and how to craft enriched nikolite ingot.

**Steps to Reproduce:**
- Create a Fabric 1.20.1 world
- Install Industrial Revolution (optionally JEI too)
- Figure out where the recipe is for : Bronze dust/ingot, enriched nikolite/ingot, electrum.

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: 0.14.24
 - Industrial Revolution: indrev-1.16.5-BETA
 - Modpack: none

**Logs:**
- No need.

**Details:**
Description is clear enough. But here's a proof that nikolite ingot not showing up on JEI menu :

![indrev bug](https://github.com/GabrielOlvH/Industrial-Revolution/assets/10588005/6b67d9bf-63ca-4692-81dd-465409ecb5b7)

**Comment by RemagOfficial** [comment]
use REI not JEI, JEI is not supported

**Comment by DevKemal** [comment]
> use REI not JEI, JEI is not supported

That solved it, thanks!
