### ISSUE TITLE
[BUG] Interacting with Modular Workbench crashes the Server

### ISSUE THREAD

**Issue by burdoto** [GabrielOlvH/Industrial-Revolution#578]
**Description:**
When interacting with a Modular Workbench; the server crashes due to a `NoClassDefFoundException`

**Steps to Reproduce:**
unknown

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: fabric-api-0.91.11.20.1
 - Industrial Revolution: indrez-1.16.5-BETA-Hotfix
 - Modpack: All the Fabric v5.5

**Logs:**
Exception: https://www.toptal.com/developers/hastebin
[crash-2024-03-27_16.56.21-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/14779299/crash-2024-03-27_16.56.21-server.txt)

**Details:**
I am aware that the server is running Arclight which may introduce extra incompatibilities, but since the NCDFEx points to a vanilla minecraft class, I wouldn't say that Arclight is at fault here.

**Comment by Kodikuu** [comment]
I have the exact same issue on All of Fabric 7 v2.0.2;
- Minecraft: 1.20.1
- Fabric API: fabric-api-0.92.0+1.20.1
- Indrev: indrev-1.16.5-BETA-Hotfix
- Modpack: All of Fabric 7 v2.0.2

Crashlog (identical to trace in OP's log):
[crash-2024-04-13_17.59.05-server.txt](https://github.com/GabrielOlvH/Industrial-Revolution/files/14968149/crash-2024-04-13_17.59.05-server.txt)

**Comment by Sanlovty** [comment]
@Kodikuu @burdoto Change the version of mod - swap (indrez-1.16.5-BETA-Hotfix) with last release ( indrev-1.16.7-BETA.jar). It fixes the problem

**Comment by burdoto** [comment]
thank you - the issue has been resolved
