### ISSUE TITLE
[BUG] Cannot start server by modelProvider

### ISSUE THREAD

**Issue by Aluzquizz** [GabrielOlvH/Industrial-Revolution#605]
Description:
  Mising modelProvider

Technical Information:
 - Minecraft: 1.19.2
 - Fabric API: 0.16.5
 - Industrial Revolution: 1.15.1
 
Logs:
[log.log](https://github.com/user-attachments/files/17005181/log.log)

Details:

This error happened to me when I put a ModPack created by me on my server. When I started it I got this error.
I've been looking for information but I don't have enough programming knowledge to understand it.
It has to do with this
---MachineRegistry.kt------
59: val modelProvider: MutableMap<Tier, (String) -> UnbakedModel?> = EnumMap(Tier::class.java)
188: val COAL_GENERATOR_REGISTRY = MachineRegistry("coal_generator", false, Tier.MK1)
---IndustrialRevolution.kt------
60: MachineRegistry

**Comment by Poopooracoocoo** [comment]
Also see https://github.com/GabrielOlvH/Industrial-Revolution/issues/566#issuecomment-2068195884

**Comment by Aluzquizz** [comment]
thx Ands work in my server
