### ISSUE TITLE
[BUG] Missing language key

### ISSUE THREAD

**Issue by Romz24** [GabrielOlvH/Industrial-Revolution#66]
I don't know what this button is responsible for, so I decided to write about it here instead of creating **Pull requests**.

```
"key.indrev.modular": "text",
"category.indrev": "Industrial Revolution",
```

**Comment by GabrielOlvH** [comment]
I already added this in the dev branch. This opens up the screen so you can customize/disable modules from your modular armor and tools. Thanks for the report anyway!
