### ISSUE TITLE
[BUG] [1.16.3] Improved fisher give only generic "Enchanted Book"

### ISSUE THREAD

**Issue by ProsperCraft** [GabrielOlvH/Industrial-Revolution#69]
**Description:**
- Give a detailed explanation of the issue

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft:  1.16.3
 - Fabric API: fabric-api-0.25.0+build.415-1.16
 - Industrial Revolution: indrev-1.7.3-BETA.jar
 - Modpack: [The Adventures of Halk for 1.16](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk/)

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.
![2020-11-05_22 05 09](https://user-images.githubusercontent.com/4427684/98328486-15c87d80-1fb3-11eb-9ce9-7fce690ef5aa.png)

**Comment by GabrielOlvH** [comment]
Fixed as of 1.7.4, thanks for reporting!
