### ISSUE TITLE
Condenser is not running

### ISSUE THREAD

**Issue by CrimsonCobra817** [GabrielOlvH/Industrial-Revolution#70]
**Description:**
- Give a detailed explanation of the issue

**Technical Information:**
 -Minecraft: 1.16.3
 - Fabric API: fabric-api-0.25.0+build.415-1.16
 -Industrial Revolution: indrev-1.7.3-BETA.jar
 - Modpack: The Adventures of Halk for 1.16

**Details:**
Condenser is not running in Multiplayer or Single player. 

![Set up](https://user-images.githubusercontent.com/62084476/98344098-5edef880-1fd8-11eb-843b-fce027588a55.png)
![Item in question](https://user-images.githubusercontent.com/62084476/98344113-630b1600-1fd8-11eb-942f-c11f8212eed1.png)

**Comment by GabrielOlvH** [comment]
Fixed as of 1.7.4, thanks for reporting!
