### ISSUE TITLE
Item Movement with a pipe

### ISSUE THREAD

**Issue by CrimsonCobra817** [GabrielOlvH/Industrial-Revolution#73]
**Description:**
- A way to move items from items and or Fluids

**Reason:**
It would allow for more automation of systems

**Comment by GabrielOlvH** [comment]
These are quite tricky for implementing. I have plans that definitely could use some fluid pipes but this might take a while. For the now, you can use Applied Energistics 2 or Modern Industrialization's pipes for this

**Comment by GabrielOlvH** [comment]
Finally implemented in 1.9.0 which can be downloaded on curseforge.
