### ISSUE TITLE
[VISUAL BUG] Gamer axe

### ISSUE THREAD

**Issue by LouiJ** [GabrielOlvH/Industrial-Revolution#74]
-  When **right-clicking with the gamer axe equipped** (to activate it) it shortly transforms into a sick-looking axe, but then **transforms back to a stick**. It sometime stays in axe mode for 1 or 2 seconds, but most of the time only 0.5s or less.

EDIT : Installing the Fire Aspect module doesn't do anything. Might just be a consequence to the previous bug ?

I believe this is a bug, if not, I'd love an explanation on how to keep the gamer axe in axe mode.
Love the mod, keep up the good work

**Comment by GabrielOlvH** [comment]
Just making sure, does it have energy?

**Comment by LouiJ** [comment]
Alright, I guess I'm just dumb lol. Thank you for your quick reaction !

PS : Maybe a prompt "Out of energy" could help ?

**Comment by GabrielOlvH** [comment]
I'll add a message for that, thanks!
