### ISSUE TITLE
[BUG] Factories

### ISSUE THREAD

**Issue by LouiJ** [GabrielOlvH/Industrial-Revolution#75]
**Description:**
- When I try to assemble a factory it goes like this : 
I put the factory block down, and right click it.
A ghost image of where I should place the other blocs appears (9 frames on the bottom, 6 silos + 2 cabinet + 1 controller above that, and then 3 ducts + 3 intakes + 1 warning strobe on top).
I place the blocs corresponding in their position and some of them glow white.
When I right click on the factory again, it says : "Stucture not built"

I feel like the white glow indicates that the bloc is correctly positionned, but I CANNOT get some blocs to glow white. And placing random blocs (such as sand) glow white !

**Technical Information:**
 - Minecraft: 1.16.3
 - Fabric API: 0.25.1+build.416-1.16
 - Industrial Revolution: 1.7.7
 - Mods: BetterCaves, Byg, cinderscape, CreeperConfetti, Nethereu, oprifabric, oprifine, patchouli, repurposed structures, REI, SimpleBackpack, Simpleportals, vanilladeathchests, vanillahammers

PS : Love the mod, keep up the good work

**Comment by GabrielOlvH** [comment]
The "white glow" should be red to identify a misplaced block. Probably Optifine messed with this. Can you provide a screenshot of your factory?

**Comment by LouiJ** [comment]
So I made a few tests, and the fact that the factory was not working is because I misoriented the cabinets.

And the glow is indeed messed up, most likely by optifine (changing shaders didn't change anything).
So my issue is fixed, thank you !
