### ISSUE TITLE
[REQUEST] Drill offset on modular drill

### ISSUE THREAD

**Issue by Reveter** [GabrielOlvH/Industrial-Revolution#76]
**Description:**
When mining horizontally, with a range enhanced modular drill, offset the center of the block breaking area upwards to avoid mining the floor in front you.

**Reason:**
Mining with a max range modular drill is currently very difficult as you end up breaking the blocks below you.

**Comment by GabrielOlvH** [comment]
This is currently not supported by Magna (which handles the animation, outlines and mining for AOE tools). I'll look into this again in the future. Thanks for the suggestion!

**Comment by Garueri** [comment]
yeah I'm a complete idiot, I just wrote a book to read because I didn't check here before
