### ISSUE TITLE
[BUG] Getting an Error on Startup of Minecraft

### ISSUE THREAD

**Issue by ZaneDragonBorn** [GabrielOlvH/Industrial-Revolution#77]
**Description:**
When Starting Minecraft it'll crash with this error

**Steps to Reproduce:**
Start Minecraft with the 130+ mods I have installed lmao

**Technical Information:**
 - Minecraft: 1.16.2
 - Fabric API: 0.10.6+build.214
 - Industrial Revolution: 1.7.8 Beta
 - Modpack: My Own

**Logs:**
https://pastebin.com/AXVTCEtf

**Comment by GabrielOlvH** [comment]
That is a very old Fabric API, try updating

**Comment by GabrielOlvH** [comment]
I'll close this for now, if the issue persists with an updated Fabric API, please reopen the issue.
