### ISSUE TITLE
[BUG] Night vision doesn't do anything.

### ISSUE THREAD

**Issue by ProsperCraft** [GabrielOlvH/Industrial-Revolution#79]
**Description:**
https://github.com/AztechMC/Modern-Industrialization/issues/29

**Technical Information:**
 - Minecraft: 1.16.3
 - Fabric API: fabric-api-0.25.0+build.415-1.16
 - Industrial Revolution: indrev-1.7.8-BETA
 - Modpack: [The Adventures of Halk](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk)

**Comment by GabrielOlvH** [comment]
Will be fixed in the next release, thanks for the report!
