### ISSUE TITLE
[BUG] Night Vision Module doesn't provide the Night Vision effect

### ISSUE THREAD

**Issue by Dathide** [GabrielOlvH/Industrial-Revolution#80]
**Description:**
After installing the Night Vision Module on a Modular Helmet, charging it, and equipping it underground in a cave, there is no Night Vision effect provided. The normal potion effect makes caves bright as day while this upgrade doesn't show that Night Vision is active in the inventory where active potion effects are shown. It only seems to make above-ground lighting a bit brighter at night, making it far less useful.

**Steps to Reproduce:**
1. Install a Night Vision Module on a charged Modular Helmet.
2. Enter a dark cave with no lighting.
3. Equip the helmet from Step 1.
4. Observe that the cave isn't any brighter. 
5. Close and open inventory, where there is an absence of an active potion effect to the left of the grid.

**Technical Information:**
 - Minecraft: 1.16.3
 - Fabric API: 0.25.4+1.16
 - Industrial Revolution: 1.7.8-BETA
 - Modpack: All of Fabric 3 2.4.0

**Logs:**
No logs necessary, but will provide them if needed.

**Details:**
![2020-11-12_16 38 04](https://user-images.githubusercontent.com/47128084/99009610-87e61880-2505-11eb-91bf-98b581da6e39.png)
![2020-11-12_16 38 15](https://user-images.githubusercontent.com/47128084/99009628-8d436300-2505-11eb-99ac-45cea81cecb9.png)

**Comment by GabrielOlvH** [comment]
Duplicate from https://github.com/GabrielOlvH/Industrial-Revolution/issues/79. It's fixed and will be released with the next update.
Thanks for the report.
