### ISSUE TITLE
[REQUEST] Modular Workbench can remove modules from equipment

### ISSUE THREAD

**Issue by Dathide** [GabrielOlvH/Industrial-Revolution#81]
**Description:**
I suggest that the Modular Workbench be modified so that it can remove modules from Modular Helmets, Chestplates, Leggings, Boots, Drills, and Gamer Axes. For example, a player can put a Modular Helmet with Protection 1 and Solar Panel 1 into the top slot of the Modular Workbench (instead of the usual bottom slot). On the purple screen, the player can choose which Module to remove. Once they click on one of them, the process of removing it starts, which takes the same amount of time and power as installing the Module.

**Reason:**
These are highly expensive pieces of equipment, costing multiple diamonds and other resources like Netherite Ingots to make. There are multiple Modules that might be installed by mistake or players may decide they no longer want them. For example, a player might think the "Range Module" means that they can reach blocks further away from them once installed on their drill. After they install it, they realize that it instead now breaks a 3x3 square at a time, which they didn't want. They now need to remake the entire drill to get one without that Module. Or maybe a player wants to switch from Silk Touch to Fortune on their drill. Or they install a Speed Module on their leggings and realize that they now move too fast for them to play the game comfortably. Or a color module is installed that a player realizes they don't like the look of. There are many examples I could provide.

**Comment by GabrielOlvH** [comment]
You don't have to remove modules to switch or disable effects, you can use the modular configuration screen to change the levels. Its key is unbinded by default but you can change it in the keybinds screen in minecraft

**Comment by Dathide** [comment]
Wow, that is very useful. Maybe put a sentence in the Revolutionary Guide book about this, for each item that Modules work on?

**Comment by GabrielOlvH** [comment]
Yeah I'll add more information about this in the guide book. Thanks for the suggestion!
