### ISSUE TITLE
[BUG] Base Modular Mining Drill vein mines like a hammer with Diggus Maximus

### ISSUE THREAD

**Issue by Dathide** [GabrielOlvH/Industrial-Revolution#82]
**Description:**
When holding the ~ key and mining with a Modular Mining Drill (MMD) that has no upgrades, only the blocks in a certain direction are mined. The other drills (MK1-MK3) have the expected vein mining behavior. I suspect that the MMD may have been given the same vein mining properties as hammers because it can be upgraded to mine 3x3-11x11 areas. This is useful when using the MMD and ~ key is used in hammer mode, but the issue arises when this is turned off or these upgrades aren't applied. Without upgrades, the MMD can only mine one block at a time like a pickaxe. It is impossible to vein mine blocks like coal ore when mining with an MMD, meaning that regular pickaxes and the lower grade drills are more useful in regular mining circumstances. Ideally, the MMD would use hammer Diggus mode when the Range Modules are turned on, and use the regular Diggus mode when the Range Modules are turned off or not applied.

**Steps to Reproduce:**
1. Install Diggus Maximus.
2. Obtain a charged Modular Mining Drill with no upgrades.
3. Attempt to vein mine a coal ore vein with the ~ key held.

**Technical Information:**
 - Minecraft: 1.16.3
 - Fabric API: 0.25.4+1.16
 - Industrial Revolution: 1.7.8-BETA
 - Modpack: All of Fabric 3 2.4.1

**Logs:**
I don't think a log is needed.

**Details:**
![2020-11-13_15 09 20](https://user-images.githubusercontent.com/47128084/99132937-50df3800-25d5-11eb-976c-61bb9451ee55.png)

**Comment by GabrielOlvH** [comment]
Sneaking while vein mining could possibly be a workaround for this issue for now.

**Comment by BobPIckle1** [comment]
vat in good curry
