### ISSUE TITLE
[BUG] Something wrong with the fisher

### ISSUE THREAD

**Issue by Okeus802** [GabrielOlvH/Industrial-Revolution#88]
**Description:**
The fisher randomly crashes the game.

**Steps to Reproduce:**
I have a fisher set up with a hopper underneath, that connects to my storage network. I also have a hopper set up to auto-feed it fishing rods. It's the second tier of the fisher. This is all I can think of that relates to it. I'll be sitting kind of afk, waiting for machines to do things and I get this crash.

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.27.1
 - Industrial Revolution: 1.7.15 Beta
 - Modpack: All of Fabric 3 2.5.2

**Logs:**
https://pastebin.com/mXPi1nrr

**Details:**
I'm running a kind of custom build of All of Fabric, I call it AoF+. My laptop isn't phenomenal, and I do get random other crashes but I've been getting this one pretty consistently, and figured I'd report it! Good luck, and thanks for all your hard work!

**Comment by GabrielOlvH** [comment]
Thank you for reporting, could you try reproducing this crash with [this mod](https://github.com/comp500/mixintrace/tree/1.0.0)? It should provide helpful information about this crash.

**Comment by Okeus802** [comment]
Oh weird! Thanks!
