### ISSUE TITLE
[BUG] Efficiency Upgrade is working as a flat decrease

### ISSUE THREAD

**Issue by MissPotato** [GabrielOlvH/Industrial-Revolution#89]
**Description:**
- Energy Efficiency Upgrades are only reducing power by a flat .1 LF per tick. I'm guessing it's supposed to be a % as the default is a decimal. Currently, the upgrade is negligible as it would take 80 of them to have the equivalent of a single solar generator.
 
**Steps to Reproduce:**
Easy way to tell is to fill a machine buffer to full, run it with no upgrades vs full upgrades.

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.28.1 1.16
 - Industrial Revolution: 1.7.15-beta
 - Modpack: All of Fabric 3 - 2.5.4

**Logs:**
https://paste.ee/p/AYGPk (Not sure if still needed

**Details:**
- Setup One https://i.imgur.com/c0q1Foo.png https://i.imgur.com/zEZEZuU.png
- Setup Two https://i.imgur.com/yixN5r3.png https://i.imgur.com/aTKwvJo.png

**Comment by GabrielOlvH** [comment]
That is indeed a mistake, it's already fixed in the development version, thanks for reporting!

**Comment by GabrielOlvH** [comment]
Should be fixed in 1.8.0
