### ISSUE TITLE
Crash when taking falling damage (1.16.1 - 0.5.0-BETA)

### ISSUE THREAD

**Issue by Katorone** [GabrielOlvH/Industrial-Revolution#9]
After adding this mod, taking falling damage crashes the server:
https://pastebin.com/hLh9aq4w

**Comment by GabrielOlvH** [comment]
Oh, I'm very sorry, I already found the issue and will be sending a fix right now. I'll reply here again as soon as it is available on curseforge.

**Comment by GabrielOlvH** [comment]
Fixed in 0.5.1-BETA, you can download it [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3004573). I'm very sorry about this problem!

**Comment by Katorone** [comment]
Thank you very much!  I'm looking forward to exploring this mod.
I can confirm that the fix is working perfectly on my end as well.

**Comment by GabrielOlvH** [comment]
I'm glad it worked and hope you enjoy the mod!
