### ISSUE TITLE
[BUG] Mod ores scanned in wrong dimensions

### ISSUE THREAD

**Issue by Starjumper2821** [GabrielOlvH/Industrial-Revolution#91]
**Description:**
- Ores introduced by mods outside of Industrial Revolution and vanilla can appear in resource reports outside of sensible locations. For example, Certus Quartz can appear on a report in the Nether and Tech Reborn ores from the End can be mined in the desert.

**Steps to Reproduce:**
- Scan in the Nether until the resource report says Certus Quartz and use it in a Miner.

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.28.1+1.16
 - Industrial Revolution: 1.7.15-BETA
 - Applied Energistics: 8.11.0-alpha.13

**Logs:**
- Not relevant

**Details:**
![2020-12-21_11 32 41](https://user-images.githubusercontent.com/20238370/102767709-49534180-4380-11eb-9bdd-69e1e7a89f28.png)

**Comment by GabrielOlvH** [comment]
Should be fixed in 1.8.0
