### ISSUE TITLE
[BUG] Miner vein set by first report

### ISSUE THREAD

**Issue by Starjumper2821** [GabrielOlvH/Industrial-Revolution#92]
**Description:**
- The vein a Miner uses can be set by a report produced in another chunk if placed first, though it will only mine once the correct report is place.

**Steps to Reproduce:**
- Scan 2 or more chunks until 2 different resources are discovered. Place a Miner in a scanned chunk, power it and place a different report in the slot then replace it with the scan from the present chunk. Let the Miner run and it will produce resources from the first report.

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.28.1+1.16
 - Industrial Revolution: 1.7.15-BETA

**Details:**
![2020-12-21_11 37 58](https://user-images.githubusercontent.com/20238370/102768161-ff1e9000-4380-11eb-8671-94fb0d403e13.png)

**Comment by GabrielOlvH** [comment]
Should be fixed in 1.8.0
