### ISSUE TITLE
[BUG] Fluid Infuser

### ISSUE THREAD

**Issue by Romz24** [GabrielOlvH/Industrial-Revolution#94]
**Description:**
- Fluid Infuser may contain more liquid than will fit.
![unknown](https://user-images.githubusercontent.com/2458113/103577162-55ddab00-4ee5-11eb-88dd-e8021917b358.png)

**Steps to Reproduce:**
- When the right column of liquid is completely filled, I can take the liquid into the bucket, after which the mechanism will start working, at this moment you need to pour the liquid back, and the process will not stop, and at the output we will get 9000/8000

**Technical Information:**
 - Minecraft: 1.16.4
 - Fabric API: 0.28.4
 - Industrial Revolution: 1.7.15

**Comment by GabrielOlvH** [comment]
Should be fixed in 1.8.0
