### ISSUE TITLE
[BUG] Cables and Tank invisible with Sodium 

### ISSUE THREAD

**Issue by oidan** [GabrielOlvH/Industrial-Revolution#99]
Sodium causes the cables and tank to be rendered invisible

Minecraft: 1.16.4
Fabric API: 0.29.3+1.16
Industrial Revolution: 1.7.15-BETA
Sodium: 0.1.0

If I could run without sodium I would but it's pretty much essential for my laptop.

**Comment by GabrielOlvH** [comment]
Sodium currently does not support Fabric's Rendering API as it completely replaces it, this is not fixable until Sodium adds support for it.
